// AUTOGENERATED by scripts/gen-row-schemas.mjs — do not edit by hand.
// Run `pnpm --filter @pops/db-types gen:row-schemas` to regenerate.

import { createSelectSchema } from 'drizzle-zod';

import { fixtures } from './fixtures.js';

export const fixturesRowSchema = createSelectSchema(fixtures);
