// AUTOGENERATED by scripts/gen-row-schemas.mjs — do not edit by hand.
// Run `pnpm --filter @pops/db-types gen:row-schemas` to regenerate.

import { createSelectSchema } from 'drizzle-zod';

import { transactionCorrections } from './corrections.js';

export const transactionCorrectionsRowSchema = createSelectSchema(transactionCorrections);
