// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type {
  BudgetsCreateData,
  BudgetsCreateErrors,
  BudgetsCreateResponses,
  BudgetsDeleteData,
  BudgetsDeleteErrors,
  BudgetsDeleteResponses,
  BudgetsGetData,
  BudgetsGetErrors,
  BudgetsGetResponses,
  BudgetsListData,
  BudgetsListResponses,
  BudgetsUpdateData,
  BudgetsUpdateErrors,
  BudgetsUpdateResponses,
  ImportsApplyChangeSetAndReevaluateData,
  ImportsApplyChangeSetAndReevaluateErrors,
  ImportsApplyChangeSetAndReevaluateResponses,
  ImportsCommitImportData,
  ImportsCommitImportErrors,
  ImportsCommitImportResponses,
  ImportsCreateEntityData,
  ImportsCreateEntityErrors,
  ImportsCreateEntityResponses,
  ImportsExecuteImportData,
  ImportsExecuteImportErrors,
  ImportsExecuteImportResponses,
  ImportsGetImportProgressData,
  ImportsGetImportProgressErrors,
  ImportsGetImportProgressResponses,
  ImportsProcessImportData,
  ImportsProcessImportErrors,
  ImportsProcessImportResponses,
  ImportsReevaluateWithPendingRulesData,
  ImportsReevaluateWithPendingRulesErrors,
  ImportsReevaluateWithPendingRulesResponses,
  TagRulesApplyData,
  TagRulesApplyErrors,
  TagRulesApplyResponses,
  TagRulesPreviewData,
  TagRulesPreviewErrors,
  TagRulesPreviewResponses,
  TagRulesProposeData,
  TagRulesProposeErrors,
  TagRulesProposeResponses,
  TagRulesRejectData,
  TagRulesRejectErrors,
  TagRulesRejectResponses,
  TagRulesVocabularyData,
  TagRulesVocabularyResponses,
  TransactionsAvailableTagsData,
  TransactionsAvailableTagsResponses,
  TransactionsCreateData,
  TransactionsCreateErrors,
  TransactionsCreateResponses,
  TransactionsDeleteData,
  TransactionsDeleteErrors,
  TransactionsDeleteResponses,
  TransactionsDescriptionsForPreviewData,
  TransactionsDescriptionsForPreviewResponses,
  TransactionsGetData,
  TransactionsGetErrors,
  TransactionsGetResponses,
  TransactionsListData,
  TransactionsListResponses,
  TransactionsRestoreData,
  TransactionsRestoreErrors,
  TransactionsRestoreResponses,
  TransactionsSuggestTagsData,
  TransactionsSuggestTagsResponses,
  TransactionsUpdateData,
  TransactionsUpdateErrors,
  TransactionsUpdateResponses,
  WishlistCreateData,
  WishlistCreateErrors,
  WishlistCreateResponses,
  WishlistDeleteData,
  WishlistDeleteErrors,
  WishlistDeleteResponses,
  WishlistGetData,
  WishlistGetErrors,
  WishlistGetResponses,
  WishlistListData,
  WishlistListResponses,
  WishlistUpdateData,
  WishlistUpdateErrors,
  WishlistUpdateResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List budgets with optional search / period / active filters and pagination
 */
export const budgetsList = <ThrowOnError extends boolean = false>(
  options?: Options<BudgetsListData, ThrowOnError>
): RequestResult<BudgetsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<BudgetsListResponses, unknown, ThrowOnError>({
    url: '/budgets',
    ...options,
  });

/**
 * Create a budget
 */
export const budgetsCreate = <ThrowOnError extends boolean = false>(
  options?: Options<BudgetsCreateData, ThrowOnError>
): RequestResult<BudgetsCreateResponses, BudgetsCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<BudgetsCreateResponses, BudgetsCreateErrors, ThrowOnError>({
    url: '/budgets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete a budget
 */
export const budgetsDelete = <ThrowOnError extends boolean = false>(
  options: Options<BudgetsDeleteData, ThrowOnError>
): RequestResult<BudgetsDeleteResponses, BudgetsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<BudgetsDeleteResponses, BudgetsDeleteErrors, ThrowOnError>({
    url: '/budgets/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single budget (with spend aggregates)
 */
export const budgetsGet = <ThrowOnError extends boolean = false>(
  options: Options<BudgetsGetData, ThrowOnError>
): RequestResult<BudgetsGetResponses, BudgetsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<BudgetsGetResponses, BudgetsGetErrors, ThrowOnError>({
    url: '/budgets/{id}',
    ...options,
  });

/**
 * Update a budget
 */
export const budgetsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BudgetsUpdateData, ThrowOnError>
): RequestResult<BudgetsUpdateResponses, BudgetsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<BudgetsUpdateResponses, BudgetsUpdateErrors, ThrowOnError>({
    url: '/budgets/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Apply a correction ChangeSet atomically, then re-evaluate the import session
 */
export const importsApplyChangeSetAndReevaluate = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsApplyChangeSetAndReevaluateData, ThrowOnError>
): RequestResult<
  ImportsApplyChangeSetAndReevaluateResponses,
  ImportsApplyChangeSetAndReevaluateErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    ImportsApplyChangeSetAndReevaluateResponses,
    ImportsApplyChangeSetAndReevaluateErrors,
    ThrowOnError
  >({
    url: '/imports/apply-changeset-reevaluate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Atomically create entities, apply changeSets + tag-rule changeSets, write transactions
 */
export const importsCommitImport = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsCommitImportData, ThrowOnError>
): RequestResult<ImportsCommitImportResponses, ImportsCommitImportErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ImportsCommitImportResponses,
    ImportsCommitImportErrors,
    ThrowOnError
  >({
    url: '/imports/commit',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Create a new entity during an import session
 */
export const importsCreateEntity = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsCreateEntityData, ThrowOnError>
): RequestResult<ImportsCreateEntityResponses, ImportsCreateEntityErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ImportsCreateEntityResponses,
    ImportsCreateEntityErrors,
    ThrowOnError
  >({
    url: '/imports/entities',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Write confirmed transactions to SQLite; returns a session id to poll
 */
export const importsExecuteImport = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsExecuteImportData, ThrowOnError>
): RequestResult<ImportsExecuteImportResponses, ImportsExecuteImportErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ImportsExecuteImportResponses,
    ImportsExecuteImportErrors,
    ThrowOnError
  >({
    url: '/imports/execute',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Start an import process (dedup + entity matching); returns a session id to poll
 */
export const importsProcessImport = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsProcessImportData, ThrowOnError>
): RequestResult<ImportsProcessImportResponses, ImportsProcessImportErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ImportsProcessImportResponses,
    ImportsProcessImportErrors,
    ThrowOnError
  >({
    url: '/imports/process',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Poll an import session for progress (null when the session is unknown/expired)
 */
export const importsGetImportProgress = <ThrowOnError extends boolean = false>(
  options: Options<ImportsGetImportProgressData, ThrowOnError>
): RequestResult<ImportsGetImportProgressResponses, ImportsGetImportProgressErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ImportsGetImportProgressResponses,
    ImportsGetImportProgressErrors,
    ThrowOnError
  >({ url: '/imports/progress', ...options });

/**
 * Re-evaluate the import session against merged (DB + pending) rules; no DB writes
 */
export const importsReevaluateWithPendingRules = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsReevaluateWithPendingRulesData, ThrowOnError>
): RequestResult<
  ImportsReevaluateWithPendingRulesResponses,
  ImportsReevaluateWithPendingRulesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    ImportsReevaluateWithPendingRulesResponses,
    ImportsReevaluateWithPendingRulesErrors,
    ThrowOnError
  >({
    url: '/imports/reevaluate-pending',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Apply a tag-rule ChangeSet; upserts accepted new vocabulary tags
 */
export const tagRulesApply = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesApplyData, ThrowOnError>
): RequestResult<TagRulesApplyResponses, TagRulesApplyErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesApplyResponses, TagRulesApplyErrors, ThrowOnError>({
    url: '/tag-rules/apply',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Preview the suggestion-impact of a tag-rule ChangeSet over the supplied transactions
 */
export const tagRulesPreview = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesPreviewData, ThrowOnError>
): RequestResult<TagRulesPreviewResponses, TagRulesPreviewErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesPreviewResponses, TagRulesPreviewErrors, ThrowOnError>({
    url: '/tag-rules/preview',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Propose a tag-rule ChangeSet from a tag-edit signal (deterministic, with impact preview)
 */
export const tagRulesPropose = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesProposeData, ThrowOnError>
): RequestResult<TagRulesProposeResponses, TagRulesProposeErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesProposeResponses, TagRulesProposeErrors, ThrowOnError>({
    url: '/tag-rules/propose',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Reject a ChangeSet with feedback; optionally returns a revised follow-up proposal
 */
export const tagRulesReject = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesRejectData, ThrowOnError>
): RequestResult<TagRulesRejectResponses, TagRulesRejectErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesRejectResponses, TagRulesRejectErrors, ThrowOnError>({
    url: '/tag-rules/reject',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List the user tag vocabulary
 */
export const tagRulesVocabulary = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesVocabularyData, ThrowOnError>
): RequestResult<TagRulesVocabularyResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TagRulesVocabularyResponses, unknown, ThrowOnError>({
    url: '/tag-rules/vocabulary',
    ...options,
  });

/**
 * List transactions with optional filters and pagination
 */
export const transactionsList = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsListData, ThrowOnError>
): RequestResult<TransactionsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TransactionsListResponses, unknown, ThrowOnError>({
    url: '/transactions',
    ...options,
  });

/**
 * Create a transaction
 */
export const transactionsCreate = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsCreateData, ThrowOnError>
): RequestResult<TransactionsCreateResponses, TransactionsCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    TransactionsCreateResponses,
    TransactionsCreateErrors,
    ThrowOnError
  >({
    url: '/transactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Distinct tag values across all transactions (autocomplete)
 */
export const transactionsAvailableTags = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsAvailableTagsData, ThrowOnError>
): RequestResult<TransactionsAvailableTagsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TransactionsAvailableTagsResponses, unknown, ThrowOnError>({
    url: '/transactions/available-tags',
    ...options,
  });

/**
 * Descriptions (+ checksums) of existing transactions for client-side rule preview
 */
export const transactionsDescriptionsForPreview = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsDescriptionsForPreviewData, ThrowOnError>
): RequestResult<TransactionsDescriptionsForPreviewResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    TransactionsDescriptionsForPreviewResponses,
    unknown,
    ThrowOnError
  >({ url: '/transactions/descriptions-preview', ...options });

/**
 * Restore a previously-deleted transaction from its snapshot
 */
export const transactionsRestore = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsRestoreData, ThrowOnError>
): RequestResult<TransactionsRestoreResponses, TransactionsRestoreErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    TransactionsRestoreResponses,
    TransactionsRestoreErrors,
    ThrowOnError
  >({
    url: '/transactions/restore',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Rule-based tag suggestions for a description/entity (no LLM call)
 */
export const transactionsSuggestTags = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsSuggestTagsData, ThrowOnError>
): RequestResult<TransactionsSuggestTagsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<TransactionsSuggestTagsResponses, unknown, ThrowOnError>({
    url: '/transactions/suggest-tags',
    ...options,
  });

/**
 * Delete a transaction; returns a snapshot for Undo via restore
 */
export const transactionsDelete = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsDeleteData, ThrowOnError>
): RequestResult<TransactionsDeleteResponses, TransactionsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    TransactionsDeleteResponses,
    TransactionsDeleteErrors,
    ThrowOnError
  >({
    url: '/transactions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single transaction
 */
export const transactionsGet = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsGetData, ThrowOnError>
): RequestResult<TransactionsGetResponses, TransactionsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<TransactionsGetResponses, TransactionsGetErrors, ThrowOnError>({
    url: '/transactions/{id}',
    ...options,
  });

/**
 * Update a transaction
 */
export const transactionsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsUpdateData, ThrowOnError>
): RequestResult<TransactionsUpdateResponses, TransactionsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    TransactionsUpdateResponses,
    TransactionsUpdateErrors,
    ThrowOnError
  >({
    url: '/transactions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List wish-list items with optional search / priority filters and pagination
 */
export const wishlistList = <ThrowOnError extends boolean = false>(
  options?: Options<WishlistListData, ThrowOnError>
): RequestResult<WishlistListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<WishlistListResponses, unknown, ThrowOnError>({
    url: '/wishlist',
    ...options,
  });

/**
 * Create a wish-list item
 */
export const wishlistCreate = <ThrowOnError extends boolean = false>(
  options?: Options<WishlistCreateData, ThrowOnError>
): RequestResult<WishlistCreateResponses, WishlistCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<WishlistCreateResponses, WishlistCreateErrors, ThrowOnError>({
    url: '/wishlist',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete a wish-list item
 */
export const wishlistDelete = <ThrowOnError extends boolean = false>(
  options: Options<WishlistDeleteData, ThrowOnError>
): RequestResult<WishlistDeleteResponses, WishlistDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<WishlistDeleteResponses, WishlistDeleteErrors, ThrowOnError>({
    url: '/wishlist/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single wish-list item
 */
export const wishlistGet = <ThrowOnError extends boolean = false>(
  options: Options<WishlistGetData, ThrowOnError>
): RequestResult<WishlistGetResponses, WishlistGetErrors, ThrowOnError> =>
  (options.client ?? client).get<WishlistGetResponses, WishlistGetErrors, ThrowOnError>({
    url: '/wishlist/{id}',
    ...options,
  });

/**
 * Update a wish-list item
 */
export const wishlistUpdate = <ThrowOnError extends boolean = false>(
  options: Options<WishlistUpdateData, ThrowOnError>
): RequestResult<WishlistUpdateResponses, WishlistUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<WishlistUpdateResponses, WishlistUpdateErrors, ThrowOnError>({
    url: '/wishlist/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
