import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, expectTypeOf, it } from 'vitest';

import type { InventoryContract } from '../manifest.js';
import type { Item } from '../types/item.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(HERE, '..', '..');
const GENERATED_PATH = resolve(PACKAGE_ROOT, 'src', 'manifest.generated.ts');
const AUTOGENERATED_HEADER = '// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.';

describe('InventoryContract manifest type generation', () => {
  it('exposes Item on entities.item with byte-equal shape', () => {
    expectTypeOf<InventoryContract['entities']['item']>().toEqualTypeOf<Item>();
  });

  it('pins pillar discriminant and exposes errors/router slots', () => {
    expectTypeOf<InventoryContract['pillar']>().toEqualTypeOf<'inventory'>();
    expectTypeOf<InventoryContract['version']>().toEqualTypeOf<string>();
    expectTypeOf<InventoryContract>().toHaveProperty('errors');
    expectTypeOf<InventoryContract>().toHaveProperty('router');
  });

  it('emits the AUTOGENERATED header so hand-edits fail loudly', () => {
    const contents = readFileSync(GENERATED_PATH, 'utf8');
    expect(contents).toContain(AUTOGENERATED_HEADER);
  });

  it('regeneration is idempotent (no diff on a second run)', () => {
    const before = readFileSync(GENERATED_PATH, 'utf8');
    execFileSync('pnpm', ['--silent', 'run', 'generate:manifest'], {
      cwd: PACKAGE_ROOT,
      stdio: ['ignore', 'ignore', 'inherit'],
    });
    const after = readFileSync(GENERATED_PATH, 'utf8');
    expect(after).toBe(before);
  });
});
