packages:
  - 'apps/*'
  - 'packages/app-finance'
  - 'packages/app-food'
  - 'packages/app-food-db'
  - 'packages/app-lists'
  - 'packages/app-lists-db'
  - 'packages/app-media'
  - 'packages/app-inventory'
  - 'packages/app-ai'
  - 'packages/app-cerebrum'
  - 'packages/overlay-ego'
  - 'packages/api-client'
  - 'packages/core-db'
  - 'packages/finance-contract'
  - 'packages/finance-db'
  - 'packages/db-types'
  - 'packages/inventory-contract'
  - 'packages/inventory-db'
  - 'packages/media-contract'
  - 'packages/media-db'
  - 'packages/cerebrum-contract'
  - 'packages/cerebrum-db'
  - 'packages/core-contract'
  - 'packages/food-db'
  - 'packages/food-contracts'
  - 'packages/lists-contract'
  - 'packages/food-contract'
  - 'packages/lists-db'
  - 'packages/types'
  - 'packages/module-registry'
  - 'packages/navigation'
  - 'packages/pillar-sdk'
  - 'packages/ui'
