/**
 * Workspace-scan codegen for the `KNOWN_ROUTERS` catalogue (PRD-242 US-01).
 *
 * Scans `packages/*-contract/package.json`, derives the pillar id from each
 * package name (`@pops/<pillar>-contract`), and inspects `src/settings/` for
 * sub-pillar subdirectories (`cerebrum-contract` contributes `cerebrum` +
 * `ego` this way). Emits `apps/pops-api/src/generated/known-routers.ts`
 * with the imports + `KNOWN_ROUTERS_GENERATED` map, sorted by module id.
 *
 * US-01 only emits the generated catalogue — the hand-curated literal in
 * `apps/pops-api/src/router.ts` stays for now; US-03 deletes it once
 * consumers cut over.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');
const PACKAGES_DIR = join(REPO_ROOT, 'packages');
const OUT_FILE = join(HERE, '../src/generated/known-routers.ts');

interface ContractPackage {
  readonly pillar: string;
  readonly dir: string;
  readonly hasRouterExport: boolean;
  readonly subPillars: readonly string[];
}

interface ModuleEntry {
  readonly id: string;
  readonly parent: string | null;
  readonly importIdent: string;
  readonly importPath: string;
}

interface PackageJson {
  readonly name?: string;
  readonly exports?: Readonly<Record<string, unknown>>;
}

export function listContractPackageDirs(packagesDir: string): readonly string[] {
  if (!existsSync(packagesDir)) return [];
  return readdirSync(packagesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name.endsWith('-contract'))
    .map((d) => join(packagesDir, d.name))
    .toSorted();
}

export function loadContractPackage(dir: string): ContractPackage | null {
  const pkgPath = join(dir, 'package.json');
  if (!existsSync(pkgPath)) return null;
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as PackageJson;
  const name = pkg.name;
  if (typeof name !== 'string') return null;
  const match = /^@pops\/(.+)-contract$/.exec(name);
  if (match === null) return null;
  const pillar = match[1];
  const hasRouterExport =
    pkg.exports !== undefined && Object.prototype.hasOwnProperty.call(pkg.exports, './router');
  const settingsDir = join(dir, 'src', 'settings');
  const subPillars = existsSync(settingsDir)
    ? readdirSync(settingsDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .toSorted()
    : [];
  return { pillar, dir, hasRouterExport, subPillars };
}

export function collectModuleEntries(
  contracts: readonly ContractPackage[]
): readonly ModuleEntry[] {
  const entries: ModuleEntry[] = [];
  for (const c of contracts) {
    if (!c.hasRouterExport) continue;
    if (c.subPillars.length === 0) {
      entries.push({
        id: c.pillar,
        parent: null,
        importIdent: `${c.pillar}Router`,
        importPath: `../modules/${c.pillar}/index.js`,
      });
      continue;
    }
    for (const sub of c.subPillars) {
      const importPath =
        sub === c.pillar
          ? `../modules/${c.pillar}/index.js`
          : `../modules/${c.pillar}/${sub}/index.js`;
      entries.push({
        id: sub,
        parent: c.pillar,
        importIdent: `${sub}Router`,
        importPath,
      });
    }
  }
  return entries.toSorted(compareById);
}

function compareById(a: ModuleEntry, b: ModuleEntry): number {
  if (a.id < b.id) return -1;
  if (a.id > b.id) return 1;
  return 0;
}

function compareByImportPath(a: ModuleEntry, b: ModuleEntry): number {
  if (a.importPath < b.importPath) return -1;
  if (a.importPath > b.importPath) return 1;
  return 0;
}

export function renderKnownRoutersSource(entries: readonly ModuleEntry[]): string {
  const header = `/**
 * AUTOGENERATED by apps/pops-api/scripts/generate-known-routers.ts.
 * Do not edit by hand. Regenerate via \`pnpm --filter @pops/api build\`.
 *
 * Source of truth: \`packages/*-contract\` workspace packages with a
 * \`./router\` export. See PRD-242 US-01.
 */
`;
  if (entries.length === 0) {
    return `${header}\nexport const KNOWN_ROUTERS_GENERATED = {} as const;\n`;
  }
  const imports = entries
    .toSorted(compareByImportPath)
    .map((e) => `import { ${e.importIdent} } from '${e.importPath}';`)
    .join('\n');
  const body = entries.map((e) => `  ${e.id}: ${e.importIdent},`).join('\n');
  return `${header}\n${imports}\n\nexport const KNOWN_ROUTERS_GENERATED = {\n${body}\n} as const;\n`;
}

function main(): void {
  const dirs = listContractPackageDirs(PACKAGES_DIR);
  const contracts: ContractPackage[] = [];
  for (const dir of dirs) {
    const c = loadContractPackage(dir);
    if (c !== null) contracts.push(c);
  }
  const entries = collectModuleEntries(contracts);
  const source = renderKnownRoutersSource(entries);
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, source);
  console.log(`[generate-known-routers] wrote ${entries.length} entries to ${OUT_FILE}`);
}

const isMain =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main();
}
