/**
 * Media pillar manifest payload builder.
 *
 * Declares the wire-format manifest the media pillar registers with the
 * central registry on boot (opt-in via `POPS_REGISTRY_ENABLED`). The `nav` +
 * `pages` UI dimensions let the shell derive the media app-rail entry and
 * route surface from the registry walk. Source values match
 * `packages/app-media/src/routes.tsx` (icons in the kebab-case wire form
 * required by `NavConfigDescriptorSchema`).
 *
 * `routes` grows per migration slice — only domains served over REST are
 * listed. Movies is the first; later slices append their routes.
 */
import {
  arrManifest,
  mediaOperationalManifest,
  plexManifest,
  rotationManifest,
} from '../contract/settings/index.js';

import type {
  ManifestPayload,
  NavConfigDescriptor,
  PageDescriptor,
} from '@pops/pillar-sdk/manifest-schema';

export const MEDIA_PILLAR_ID = 'media' as const;

const MEDIA_NAV: NavConfigDescriptor = {
  id: 'media',
  label: 'Media',
  labelKey: 'media',
  icon: 'film',
  color: 'violet',
  basePath: '/media',
  order: 20,
  items: [
    { path: '', label: 'Library', labelKey: 'media.library', icon: 'library' },
    { path: '/watchlist', label: 'Watchlist', labelKey: 'media.watchlist', icon: 'bookmark' },
    { path: '/history', label: 'History', labelKey: 'media.history', icon: 'clock' },
    { path: '/discover', label: 'Discover', labelKey: 'media.discover', icon: 'compass' },
    { path: '/rankings', label: 'Rankings', labelKey: 'media.rankings', icon: 'trophy' },
    { path: '/search', label: 'Search', labelKey: 'media.search', icon: 'search' },
    { path: '/compare', label: 'Compare', labelKey: 'media.compare', icon: 'arrow-left-right' },
    { path: '/tier-list', label: 'Tier List', labelKey: 'media.tierList', icon: 'layers' },
  ],
};

const MEDIA_PAGES: PageDescriptor[] = [
  { path: '', index: true, bundleSlot: 'media-library' },
  { path: 'watchlist', bundleSlot: 'media-watchlist' },
  { path: 'history', bundleSlot: 'media-history' },
  { path: 'discover', bundleSlot: 'media-discover' },
  { path: 'rankings', bundleSlot: 'media-rankings' },
  { path: 'search', bundleSlot: 'media-search' },
  { path: 'compare', bundleSlot: 'media-compare' },
  { path: 'tier-list', bundleSlot: 'media-tier-list' },
];

const MEDIA_ROUTES: ManifestPayload['routes'] = {
  queries: [
    'media.movies.list',
    'media.movies.get',
    'media.tvShows.list',
    'media.tvShows.get',
    'media.tvShows.listSeasons',
    'media.tvShows.listEpisodes',
    'media.library.list',
    'media.library.genres',
    'media.library.quickPick',
    'media.watchlist.list',
    'media.watchlist.status',
    'media.watchlist.get',
    'media.watchHistory.list',
    'media.watchHistory.listRecent',
    'media.watchHistory.progress',
    'media.watchHistory.batchProgress',
    'media.watchHistory.get',
    'media.shelfImpressions.recent',
    'media.shelfImpressions.freshness',
    'media.arr.config',
    'media.arr.settings',
    'media.arr.queue',
    'media.arr.getRadarrQualityProfiles',
    'media.arr.getRadarrRootFolders',
    'media.arr.checkMovie',
    'media.arr.getMovieStatus',
    'media.arr.getSonarrQualityProfiles',
    'media.arr.getSonarrRootFolders',
    'media.arr.getSonarrLanguageProfiles',
    'media.arr.getCalendar',
    'media.arr.checkSeries',
    'media.arr.getShowStatus',
    'media.arr.getSeriesEpisodes',
    'media.plex.testConnection',
    'media.plex.getLibraries',
    'media.plex.getPlexUrl',
    'media.plex.getPlexUsername',
    'media.plex.getSyncStatus',
    'media.plex.getSectionIds',
    'media.plex.getSchedulerStatus',
    'media.plex.getSyncLogs',
    'media.comparisons.listDimensions',
    'media.comparisons.listForMedia',
    'media.comparisons.listAll',
    'media.comparisons.getSmartPair',
    'media.comparisons.scores',
    'media.comparisons.rankings',
    'media.comparisons.getStaleness',
    'media.comparisons.getTierListMovies',
    'media.rotation.listCandidates',
    'media.rotation.getCandidateStatus',
    'media.rotation.getExclusion',
    'media.rotation.sourceTypes',
    'media.rotation.listPlexFriends',
    'media.rotation.listSources',
    'media.rotation.getSettings',
  ],
  mutations: [
    'media.movies.create',
    'media.movies.update',
    'media.movies.delete',
    'media.tvShows.create',
    'media.tvShows.update',
    'media.tvShows.delete',
    'media.tvShows.createSeason',
    'media.tvShows.deleteSeason',
    'media.tvShows.createEpisode',
    'media.tvShows.deleteEpisode',
    'media.library.addMovie',
    'media.library.refreshMovie',
    'media.library.addTvShow',
    'media.library.refreshTvShow',
    'media.watchlist.add',
    'media.watchlist.update',
    'media.watchlist.reorder',
    'media.watchlist.remove',
    'media.watchHistory.log',
    'media.watchHistory.batchLog',
    'media.watchHistory.delete',
    'media.shelfImpressions.record',
    'media.shelfImpressions.cleanup',
    'media.arr.testRadarr',
    'media.arr.testRadarrSaved',
    'media.arr.downloadAndProtect',
    'media.arr.addMovie',
    'media.arr.updateRadarrMonitoring',
    'media.arr.triggerRadarrSearch',
    'media.arr.testSonarr',
    'media.arr.testSonarrSaved',
    'media.arr.updateEpisodeMonitoring',
    'media.arr.addSeries',
    'media.arr.updateSeriesMonitoring',
    'media.arr.updateSeasonMonitoring',
    'media.arr.triggerSeriesSearch',
    'media.plex.setUrl',
    'media.plex.getAuthPin',
    'media.plex.checkAuthPin',
    'media.plex.disconnect',
    'media.plex.saveSectionIds',
    'media.plex.startScheduler',
    'media.plex.stopScheduler',
    'media.comparisons.createDimension',
    'media.comparisons.updateDimension',
    'media.comparisons.record',
    'media.comparisons.delete',
    'media.comparisons.blacklistMovie',
    'media.comparisons.batchRecordComparisons',
    'media.comparisons.recordSkip',
    'media.comparisons.recalcAll',
    'media.comparisons.excludeFromDimension',
    'media.comparisons.includeInDimension',
    'media.comparisons.markStale',
    'media.comparisons.submitTierList',
    'media.rotation.addToQueue',
    'media.rotation.removeFromQueue',
    'media.rotation.downloadCandidate',
    'media.rotation.addExclusion',
    'media.rotation.removeExclusion',
    'media.rotation.createSource',
    'media.rotation.updateSource',
    'media.rotation.deleteSource',
    'media.rotation.syncSource',
    'media.rotation.saveSettings',
  ],
  subscriptions: [],
};

export function buildMediaManifest(version: string): ManifestPayload {
  return {
    pillar: MEDIA_PILLAR_ID,
    version,
    contract: {
      package: '@pops/media',
      version,
      tag: `contract-media@v${version}`,
    },
    routes: MEDIA_ROUTES,
    search: { adapters: [] },
    ai: { tools: [] },
    uri: { types: ['media/movie', 'media/tv-show', 'media/watchlist-item'] },
    consumedSettings: { keys: [] },
    settings: {
      manifests: [plexManifest, arrManifest, rotationManifest, mediaOperationalManifest],
    },
    nav: MEDIA_NAV,
    pages: MEDIA_PAGES,
    healthcheck: { path: '/health' },
  };
}
