import type { FinanceError } from './errors.js';
import type { FinanceRouter } from './router.js';
// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.
// Regenerated by `pnpm -F @pops/finance-contract generate:manifest`.
// Source version pinned at generation time: 0.1.0
import type { WishListItem } from './types/wish-list-item.js';

export interface FinanceContract {
  readonly pillar: 'finance';
  readonly version: string;
  readonly entities: {
    readonly wishListItem: WishListItem;
  };
  readonly errors: FinanceError;
  readonly router: FinanceRouter;
}
