/**
 * AUTOGENERATED by scripts/generate-api-types.ts via openapi-typescript.
 * Do not edit by hand — regenerate via `pnpm -F @pops/core generate:api-types`.
 */
export interface paths {
  '/ai-usage/cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get AI cache statistics (entry count, on-disk size) */
    get: operations['aiUsage.cacheStats'];
    put?: never;
    post?: never;
    /** Clear the entire AI cache */
    delete: operations['aiUsage.clearAllCache'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-usage/cache/prune': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Remove AI cache entries older than maxAgeDays */
    post: operations['aiUsage.clearStaleCache'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/entities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List entities with optional search / type filters and pagination */
    get: operations['entities.list'];
    put?: never;
    /** Create an entity */
    post: operations['entities.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/entities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single entity */
    get: operations['entities.get'];
    put?: never;
    post?: never;
    /** Delete an entity */
    delete: operations['entities.delete'];
    options?: never;
    head?: never;
    /** Update an entity */
    patch: operations['entities.update'];
    trace?: never;
  };
  '/features': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resolved feature status for the current user (admin Features page) */
    get: operations['features.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/features/manifests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all registered feature manifests (sorted by order) */
    get: operations['features.getManifests'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/features/{key}/enabled': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runtime gate for a single feature in the current user context (404 on unknown key) */
    get: operations['features.isEnabled'];
    /** Set the system-level enabled state (400 when the gate is failing) */
    put: operations['features.setEnabled'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/features/{key}/preference': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set a per-user override (400 when the feature is not user-scoped) */
    put: operations['features.setUserPreference'];
    post?: never;
    /** Remove a per-user override (resolution falls back to the system default) */
    delete: operations['features.clearUserPreference'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search the core pillar's domains (entities) for the unified search engine */
    post: operations['search.search'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/service-accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List service accounts (admin only) */
    get: operations['serviceAccounts.list'];
    put?: never;
    /** Mint a service account and return its one-time plaintext key (admin only) */
    post: operations['serviceAccounts.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/service-accounts/{id}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a service account by id (admin only) */
    post: operations['serviceAccounts.revoke'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List effective values for every declared key (sensitive redacted) */
    get: operations['settings.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/get-many': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Batch-read settings by key (missing omitted; sensitive redacted) */
    post: operations['settings.getMany'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset declared keys to defaults (omit keys ⇒ reset all) */
    post: operations['settings.reset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/set-many': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transactional batch write (all-or-nothing); returns the written mirror */
    post: operations['settings.setMany'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a single setting (null on unset; sensitive redacted) */
    get: operations['settings.get'];
    /** Upsert a single declared setting */
    put: operations['settings.set'];
    post?: never;
    /** Reset a single setting to its default (legacy DELETE alias for the reset route) */
    delete: operations['settings.delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/{key}/ensure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Internal-only write-once seed (encryption seed / client id) */
    post: operations['settings.ensure'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/{key}/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset a single setting to its manifest default */
    post: operations['settings.resetKey'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/shell/manifest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the boot-time install manifest (installed apps + overlays) */
    get: operations['shell.manifest'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resolve a user URI (pops://core/user/<email>) for cross-pillar reconciliation */
    get: operations['users.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'aiUsage.cacheStats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            diskSizeBytes: number;
            totalEntries: number;
          };
        };
      };
    };
  };
  'aiUsage.clearAllCache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            removed: number;
          };
        };
      };
    };
  };
  'aiUsage.clearStaleCache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          /** @default 30 */
          maxAgeDays: number;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            removed: number;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'entities.list': {
    parameters: {
      query?: {
        search?: string;
        type?: 'company' | 'person' | 'government' | 'bank' | 'place' | 'brand' | 'organisation';
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              abn: string | null;
              aliases: string[];
              defaultTags: string[];
              defaultTransactionType: string | null;
              id: string;
              lastEditedTime: string;
              name: string;
              notes: string | null;
              type: string;
            }[];
            pagination: {
              hasMore: boolean;
              limit: number;
              offset: number;
              total: number;
            };
          };
        };
      };
    };
  };
  'entities.create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          abn?: string | null;
          /** @default [] */
          aliases: string[];
          /** @default [] */
          defaultTags: string[];
          defaultTransactionType?: string | null;
          name: string;
          notes?: string | null;
          /**
           * @default company
           * @enum {string}
           */
          type: 'company' | 'person' | 'government' | 'bank' | 'place' | 'brand' | 'organisation';
        };
      };
    };
    responses: {
      /** @description 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              abn: string | null;
              aliases: string[];
              defaultTags: string[];
              defaultTransactionType: string | null;
              id: string;
              lastEditedTime: string;
              name: string;
              notes: string | null;
              type: string;
            };
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'entities.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              abn: string | null;
              aliases: string[];
              defaultTags: string[];
              defaultTransactionType: string | null;
              id: string;
              lastEditedTime: string;
              name: string;
              notes: string | null;
              type: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'entities.delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'entities.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          abn?: string | null;
          aliases?: string[];
          defaultTags?: string[];
          defaultTransactionType?: string | null;
          name?: string;
          notes?: string | null;
          /** @enum {string} */
          type?: 'company' | 'person' | 'government' | 'bank' | 'place' | 'brand' | 'organisation';
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              abn: string | null;
              aliases: string[];
              defaultTags: string[];
              defaultTransactionType: string | null;
              id: string;
              lastEditedTime: string;
              name: string;
              notes: string | null;
              type: string;
            };
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'features.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            features: {
              capabilityMissing?: boolean;
              configureLink?: string;
              credentials: {
                envVar?: string;
                key: string;
                /** @enum {string} */
                source: 'database' | 'environment' | 'missing';
              }[];
              default: boolean;
              deprecated?: boolean;
              description?: string;
              enabled: boolean;
              key: string;
              label: string;
              manifestId: string;
              preview?: boolean;
              /** @enum {string} */
              scope: 'system' | 'user' | 'capability';
              /** @enum {string} */
              state: 'enabled' | 'disabled' | 'unavailable';
              userOverride?: boolean;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'features.getManifests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            manifests: {
              features: {
                configureLink?: string;
                default: boolean;
                deprecated?: boolean;
                description?: string;
                key: string;
                label: string;
                preview?: boolean;
                requires?: string[];
                requiresEnv?: string[];
                /** @enum {string} */
                scope: 'system' | 'user' | 'capability';
                settingKey?: string;
              }[];
              icon?: string;
              id: string;
              order: number;
              title: string;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'features.isEnabled': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            enabled: boolean;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'features.setEnabled': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          enabled: boolean;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            enabled: boolean;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'features.setUserPreference': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          enabled: boolean;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            enabled: boolean;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'features.clearUserPreference': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            cleared: boolean;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'search.search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          context?: {
            app: string | null;
            entity?: {
              title: string;
              type: string;
              uri: string;
            };
            filters?: {
              [key: string]: string;
            };
            page: string | null;
          };
          query: {
            filters?: {
              field: string;
              operator: string;
              value: string;
            }[];
            text: string;
          };
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            hits: {
              data: {
                [key: string]: unknown;
              };
              matchField: string;
              /** @enum {string} */
              matchType: 'exact' | 'prefix' | 'contains';
              score: number;
              uri: string;
            }[];
          };
        };
      };
    };
  };
  'serviceAccounts.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            createdAt: string;
            createdBy: string | null;
            id: string;
            keyPrefix: string;
            lastUsedAt: string | null;
            name: string;
            revokedAt: string | null;
            scopes: string[];
          }[];
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'serviceAccounts.create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          name: string;
          scopes: string[];
        };
      };
    };
    responses: {
      /** @description 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            createdAt: string;
            createdBy: string | null;
            id: string;
            keyPrefix: string;
            lastUsedAt: string | null;
            name: string;
            plaintextKey: string;
            revokedAt: string | null;
            scopes: string[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'serviceAccounts.revoke': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.getMany': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          keys: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            settings: {
              [key: string]: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          keys?: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            reset: string[];
            settings: {
              [key: string]: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.setMany': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          entries: {
            key: string;
            value: string;
          }[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            settings: {
              [key: string]: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'plex_url'
          | 'plex_token'
          | 'plex_username'
          | 'plex_encryption_seed'
          | 'plex_client_identifier'
          | 'plex_movie_section_id'
          | 'plex_tv_section_id'
          | 'plex_scheduler_enabled'
          | 'plex_scheduler_interval_ms'
          | 'radarr_url'
          | 'radarr_api_key'
          | 'sonarr_url'
          | 'sonarr_api_key'
          | 'ai.model'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'cerebrum.query.maxSources'
          | 'cerebrum.query.relevanceThreshold'
          | 'cerebrum.query.tokenBudget'
          | 'cerebrum.emit.maxTokens'
          | 'cerebrum.emit.relevanceThreshold'
          | 'cerebrum.emit.maxSources'
          | 'cerebrum.emit.tokenBudget'
          | 'cerebrum.semantic.defaultLimit'
          | 'cerebrum.semantic.defaultThreshold'
          | 'cerebrum.semantic.queryCacheTtl'
          | 'cerebrum.hybrid.rrfK'
          | 'cerebrum.hybrid.defaultLimit'
          | 'cerebrum.hybrid.defaultThreshold'
          | 'cerebrum.context.tokenBudget'
          | 'cerebrum.classifier.confidenceThreshold'
          | 'cerebrum.entityExtractor.confidenceThreshold'
          | 'cerebrum.captureHotkey'
          | 'cerebrum.nudge.consolidationSimilarity'
          | 'cerebrum.nudge.consolidationMinCluster'
          | 'cerebrum.nudge.stalenessDays'
          | 'cerebrum.nudge.patternMinOccurrences'
          | 'cerebrum.nudge.maxPending'
          | 'cerebrum.nudge.cooldownHours'
          | 'cerebrum.engram.fallbackScope'
          | 'cerebrum.citation.excerptMaxLength'
          | 'cerebrum.plexus.healthIntervalMs'
          | 'cerebrum.plexus.healthTimeoutMs'
          | 'cerebrum.plexus.maxConsecutiveFailures'
          | 'cerebrum.thalamus.crossSourceIntervalMs'
          | 'cerebrum.mcp.queryMaxSources'
          | 'cerebrum.mcp.searchSnippetLength'
          | 'cerebrum.mcp.searchDefaultLimit'
          | 'cerebrum.glia.proposeMinApproved'
          | 'cerebrum.glia.proposeMaxRejectionRate'
          | 'cerebrum.glia.actReportMinDays'
          | 'cerebrum.glia.demotionRevertThreshold'
          | 'cerebrum.glia.demotionWindowDays'
          | 'ego.defaultModel'
          | 'ego.maxHistory'
          | 'ego.maxRetrieval'
          | 'ego.tokenBudget'
          | 'ego.relevanceThreshold'
          | 'ego.chat.maxTokens'
          | 'ego.chat.temperature'
          | 'ego.summary.maxTokens'
          | 'ego.summary.temperature'
          | 'media.comparisons.eloK'
          | 'media.comparisons.defaultScore'
          | 'media.comparisons.maxTierListMovies'
          | 'media.comparisons.stalenessThreshold'
          | 'media.comparisons.defaultLimit'
          | 'media.discovery.sessionTargetMin'
          | 'media.discovery.sessionTargetMax'
          | 'media.discovery.maxSeedShelves'
          | 'media.discovery.maxGenreShelves'
          | 'media.discovery.maxActiveCollections'
          | 'media.discovery.maxBecauseYouWatchedSeeds'
          | 'media.discovery.maxCreditsSeeds'
          | 'media.discovery.maxBestInGenre'
          | 'media.discovery.maxCrossoverPairs'
          | 'media.thetvdb.rateLimitCapacity'
          | 'media.thetvdb.rateLimitRefillRate'
          | 'media.thetvdb.maxRetries'
          | 'media.tmdb.genreCacheTtlMs'
          | 'media.tmdb.imageMaxRetries'
          | 'media.tmdb.imageRetryDelayMs'
          | 'media.plex.rateLimitDelayMs'
          | 'media.plex.clientPageSize'
          | 'media.plex.friendsPageSize'
          | 'media.defaultLimit'
          | 'media.rotation.tmdbDefaultPages'
          | 'media.rotation.tmdbMaxPages'
          | 'media.rotation.tmdbMinVoteCount'
          | 'media.rotation.letterboxdMaxPages'
          | 'finance.aiCategorizer.model'
          | 'finance.aiCategorizer.maxTokens'
          | 'finance.ruleGen.model'
          | 'finance.ruleGen.maxTokens'
          | 'finance.defaultLimit'
          | 'inventory.defaultLimit'
          | 'inventory.searchDefaultLimit'
          | 'inventory.maxFileSizeBytes'
          | 'core.corrections.highConfidenceThreshold'
          | 'core.corrections.minPatternLength'
          | 'core.corrections.previewLimit'
          | 'core.corrections.previewHardLimit'
          | 'core.corrections.previewRulesFetchLimit'
          | 'core.search.showMoreLimit'
          | 'core.aiRetry.maxRetries'
          | 'core.aiRetry.baseDelayMs'
          | 'core.defaultLimit'
          | 'core.queue.syncConcurrency'
          | 'core.queue.embeddingsConcurrency'
          | 'core.queue.defaultConcurrency'
          | 'core.queue.completedRetention'
          | 'theme';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            } | null;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.set': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'plex_url'
          | 'plex_token'
          | 'plex_username'
          | 'plex_encryption_seed'
          | 'plex_client_identifier'
          | 'plex_movie_section_id'
          | 'plex_tv_section_id'
          | 'plex_scheduler_enabled'
          | 'plex_scheduler_interval_ms'
          | 'radarr_url'
          | 'radarr_api_key'
          | 'sonarr_url'
          | 'sonarr_api_key'
          | 'ai.model'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'cerebrum.query.maxSources'
          | 'cerebrum.query.relevanceThreshold'
          | 'cerebrum.query.tokenBudget'
          | 'cerebrum.emit.maxTokens'
          | 'cerebrum.emit.relevanceThreshold'
          | 'cerebrum.emit.maxSources'
          | 'cerebrum.emit.tokenBudget'
          | 'cerebrum.semantic.defaultLimit'
          | 'cerebrum.semantic.defaultThreshold'
          | 'cerebrum.semantic.queryCacheTtl'
          | 'cerebrum.hybrid.rrfK'
          | 'cerebrum.hybrid.defaultLimit'
          | 'cerebrum.hybrid.defaultThreshold'
          | 'cerebrum.context.tokenBudget'
          | 'cerebrum.classifier.confidenceThreshold'
          | 'cerebrum.entityExtractor.confidenceThreshold'
          | 'cerebrum.captureHotkey'
          | 'cerebrum.nudge.consolidationSimilarity'
          | 'cerebrum.nudge.consolidationMinCluster'
          | 'cerebrum.nudge.stalenessDays'
          | 'cerebrum.nudge.patternMinOccurrences'
          | 'cerebrum.nudge.maxPending'
          | 'cerebrum.nudge.cooldownHours'
          | 'cerebrum.engram.fallbackScope'
          | 'cerebrum.citation.excerptMaxLength'
          | 'cerebrum.plexus.healthIntervalMs'
          | 'cerebrum.plexus.healthTimeoutMs'
          | 'cerebrum.plexus.maxConsecutiveFailures'
          | 'cerebrum.thalamus.crossSourceIntervalMs'
          | 'cerebrum.mcp.queryMaxSources'
          | 'cerebrum.mcp.searchSnippetLength'
          | 'cerebrum.mcp.searchDefaultLimit'
          | 'cerebrum.glia.proposeMinApproved'
          | 'cerebrum.glia.proposeMaxRejectionRate'
          | 'cerebrum.glia.actReportMinDays'
          | 'cerebrum.glia.demotionRevertThreshold'
          | 'cerebrum.glia.demotionWindowDays'
          | 'ego.defaultModel'
          | 'ego.maxHistory'
          | 'ego.maxRetrieval'
          | 'ego.tokenBudget'
          | 'ego.relevanceThreshold'
          | 'ego.chat.maxTokens'
          | 'ego.chat.temperature'
          | 'ego.summary.maxTokens'
          | 'ego.summary.temperature'
          | 'media.comparisons.eloK'
          | 'media.comparisons.defaultScore'
          | 'media.comparisons.maxTierListMovies'
          | 'media.comparisons.stalenessThreshold'
          | 'media.comparisons.defaultLimit'
          | 'media.discovery.sessionTargetMin'
          | 'media.discovery.sessionTargetMax'
          | 'media.discovery.maxSeedShelves'
          | 'media.discovery.maxGenreShelves'
          | 'media.discovery.maxActiveCollections'
          | 'media.discovery.maxBecauseYouWatchedSeeds'
          | 'media.discovery.maxCreditsSeeds'
          | 'media.discovery.maxBestInGenre'
          | 'media.discovery.maxCrossoverPairs'
          | 'media.thetvdb.rateLimitCapacity'
          | 'media.thetvdb.rateLimitRefillRate'
          | 'media.thetvdb.maxRetries'
          | 'media.tmdb.genreCacheTtlMs'
          | 'media.tmdb.imageMaxRetries'
          | 'media.tmdb.imageRetryDelayMs'
          | 'media.plex.rateLimitDelayMs'
          | 'media.plex.clientPageSize'
          | 'media.plex.friendsPageSize'
          | 'media.defaultLimit'
          | 'media.rotation.tmdbDefaultPages'
          | 'media.rotation.tmdbMaxPages'
          | 'media.rotation.tmdbMinVoteCount'
          | 'media.rotation.letterboxdMaxPages'
          | 'finance.aiCategorizer.model'
          | 'finance.aiCategorizer.maxTokens'
          | 'finance.ruleGen.model'
          | 'finance.ruleGen.maxTokens'
          | 'finance.defaultLimit'
          | 'inventory.defaultLimit'
          | 'inventory.searchDefaultLimit'
          | 'inventory.maxFileSizeBytes'
          | 'core.corrections.highConfidenceThreshold'
          | 'core.corrections.minPatternLength'
          | 'core.corrections.previewLimit'
          | 'core.corrections.previewHardLimit'
          | 'core.corrections.previewRulesFetchLimit'
          | 'core.search.showMoreLimit'
          | 'core.aiRetry.maxRetries'
          | 'core.aiRetry.baseDelayMs'
          | 'core.defaultLimit'
          | 'core.queue.syncConcurrency'
          | 'core.queue.embeddingsConcurrency'
          | 'core.queue.defaultConcurrency'
          | 'core.queue.completedRetention'
          | 'theme';
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          value: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            };
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'plex_url'
          | 'plex_token'
          | 'plex_username'
          | 'plex_encryption_seed'
          | 'plex_client_identifier'
          | 'plex_movie_section_id'
          | 'plex_tv_section_id'
          | 'plex_scheduler_enabled'
          | 'plex_scheduler_interval_ms'
          | 'radarr_url'
          | 'radarr_api_key'
          | 'sonarr_url'
          | 'sonarr_api_key'
          | 'ai.model'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'cerebrum.query.maxSources'
          | 'cerebrum.query.relevanceThreshold'
          | 'cerebrum.query.tokenBudget'
          | 'cerebrum.emit.maxTokens'
          | 'cerebrum.emit.relevanceThreshold'
          | 'cerebrum.emit.maxSources'
          | 'cerebrum.emit.tokenBudget'
          | 'cerebrum.semantic.defaultLimit'
          | 'cerebrum.semantic.defaultThreshold'
          | 'cerebrum.semantic.queryCacheTtl'
          | 'cerebrum.hybrid.rrfK'
          | 'cerebrum.hybrid.defaultLimit'
          | 'cerebrum.hybrid.defaultThreshold'
          | 'cerebrum.context.tokenBudget'
          | 'cerebrum.classifier.confidenceThreshold'
          | 'cerebrum.entityExtractor.confidenceThreshold'
          | 'cerebrum.captureHotkey'
          | 'cerebrum.nudge.consolidationSimilarity'
          | 'cerebrum.nudge.consolidationMinCluster'
          | 'cerebrum.nudge.stalenessDays'
          | 'cerebrum.nudge.patternMinOccurrences'
          | 'cerebrum.nudge.maxPending'
          | 'cerebrum.nudge.cooldownHours'
          | 'cerebrum.engram.fallbackScope'
          | 'cerebrum.citation.excerptMaxLength'
          | 'cerebrum.plexus.healthIntervalMs'
          | 'cerebrum.plexus.healthTimeoutMs'
          | 'cerebrum.plexus.maxConsecutiveFailures'
          | 'cerebrum.thalamus.crossSourceIntervalMs'
          | 'cerebrum.mcp.queryMaxSources'
          | 'cerebrum.mcp.searchSnippetLength'
          | 'cerebrum.mcp.searchDefaultLimit'
          | 'cerebrum.glia.proposeMinApproved'
          | 'cerebrum.glia.proposeMaxRejectionRate'
          | 'cerebrum.glia.actReportMinDays'
          | 'cerebrum.glia.demotionRevertThreshold'
          | 'cerebrum.glia.demotionWindowDays'
          | 'ego.defaultModel'
          | 'ego.maxHistory'
          | 'ego.maxRetrieval'
          | 'ego.tokenBudget'
          | 'ego.relevanceThreshold'
          | 'ego.chat.maxTokens'
          | 'ego.chat.temperature'
          | 'ego.summary.maxTokens'
          | 'ego.summary.temperature'
          | 'media.comparisons.eloK'
          | 'media.comparisons.defaultScore'
          | 'media.comparisons.maxTierListMovies'
          | 'media.comparisons.stalenessThreshold'
          | 'media.comparisons.defaultLimit'
          | 'media.discovery.sessionTargetMin'
          | 'media.discovery.sessionTargetMax'
          | 'media.discovery.maxSeedShelves'
          | 'media.discovery.maxGenreShelves'
          | 'media.discovery.maxActiveCollections'
          | 'media.discovery.maxBecauseYouWatchedSeeds'
          | 'media.discovery.maxCreditsSeeds'
          | 'media.discovery.maxBestInGenre'
          | 'media.discovery.maxCrossoverPairs'
          | 'media.thetvdb.rateLimitCapacity'
          | 'media.thetvdb.rateLimitRefillRate'
          | 'media.thetvdb.maxRetries'
          | 'media.tmdb.genreCacheTtlMs'
          | 'media.tmdb.imageMaxRetries'
          | 'media.tmdb.imageRetryDelayMs'
          | 'media.plex.rateLimitDelayMs'
          | 'media.plex.clientPageSize'
          | 'media.plex.friendsPageSize'
          | 'media.defaultLimit'
          | 'media.rotation.tmdbDefaultPages'
          | 'media.rotation.tmdbMaxPages'
          | 'media.rotation.tmdbMinVoteCount'
          | 'media.rotation.letterboxdMaxPages'
          | 'finance.aiCategorizer.model'
          | 'finance.aiCategorizer.maxTokens'
          | 'finance.ruleGen.model'
          | 'finance.ruleGen.maxTokens'
          | 'finance.defaultLimit'
          | 'inventory.defaultLimit'
          | 'inventory.searchDefaultLimit'
          | 'inventory.maxFileSizeBytes'
          | 'core.corrections.highConfidenceThreshold'
          | 'core.corrections.minPatternLength'
          | 'core.corrections.previewLimit'
          | 'core.corrections.previewHardLimit'
          | 'core.corrections.previewRulesFetchLimit'
          | 'core.search.showMoreLimit'
          | 'core.aiRetry.maxRetries'
          | 'core.aiRetry.baseDelayMs'
          | 'core.defaultLimit'
          | 'core.queue.syncConcurrency'
          | 'core.queue.embeddingsConcurrency'
          | 'core.queue.defaultConcurrency'
          | 'core.queue.completedRetention'
          | 'theme';
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.ensure': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'plex_url'
          | 'plex_token'
          | 'plex_username'
          | 'plex_encryption_seed'
          | 'plex_client_identifier'
          | 'plex_movie_section_id'
          | 'plex_tv_section_id'
          | 'plex_scheduler_enabled'
          | 'plex_scheduler_interval_ms'
          | 'radarr_url'
          | 'radarr_api_key'
          | 'sonarr_url'
          | 'sonarr_api_key'
          | 'ai.model'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'cerebrum.query.maxSources'
          | 'cerebrum.query.relevanceThreshold'
          | 'cerebrum.query.tokenBudget'
          | 'cerebrum.emit.maxTokens'
          | 'cerebrum.emit.relevanceThreshold'
          | 'cerebrum.emit.maxSources'
          | 'cerebrum.emit.tokenBudget'
          | 'cerebrum.semantic.defaultLimit'
          | 'cerebrum.semantic.defaultThreshold'
          | 'cerebrum.semantic.queryCacheTtl'
          | 'cerebrum.hybrid.rrfK'
          | 'cerebrum.hybrid.defaultLimit'
          | 'cerebrum.hybrid.defaultThreshold'
          | 'cerebrum.context.tokenBudget'
          | 'cerebrum.classifier.confidenceThreshold'
          | 'cerebrum.entityExtractor.confidenceThreshold'
          | 'cerebrum.captureHotkey'
          | 'cerebrum.nudge.consolidationSimilarity'
          | 'cerebrum.nudge.consolidationMinCluster'
          | 'cerebrum.nudge.stalenessDays'
          | 'cerebrum.nudge.patternMinOccurrences'
          | 'cerebrum.nudge.maxPending'
          | 'cerebrum.nudge.cooldownHours'
          | 'cerebrum.engram.fallbackScope'
          | 'cerebrum.citation.excerptMaxLength'
          | 'cerebrum.plexus.healthIntervalMs'
          | 'cerebrum.plexus.healthTimeoutMs'
          | 'cerebrum.plexus.maxConsecutiveFailures'
          | 'cerebrum.thalamus.crossSourceIntervalMs'
          | 'cerebrum.mcp.queryMaxSources'
          | 'cerebrum.mcp.searchSnippetLength'
          | 'cerebrum.mcp.searchDefaultLimit'
          | 'cerebrum.glia.proposeMinApproved'
          | 'cerebrum.glia.proposeMaxRejectionRate'
          | 'cerebrum.glia.actReportMinDays'
          | 'cerebrum.glia.demotionRevertThreshold'
          | 'cerebrum.glia.demotionWindowDays'
          | 'ego.defaultModel'
          | 'ego.maxHistory'
          | 'ego.maxRetrieval'
          | 'ego.tokenBudget'
          | 'ego.relevanceThreshold'
          | 'ego.chat.maxTokens'
          | 'ego.chat.temperature'
          | 'ego.summary.maxTokens'
          | 'ego.summary.temperature'
          | 'media.comparisons.eloK'
          | 'media.comparisons.defaultScore'
          | 'media.comparisons.maxTierListMovies'
          | 'media.comparisons.stalenessThreshold'
          | 'media.comparisons.defaultLimit'
          | 'media.discovery.sessionTargetMin'
          | 'media.discovery.sessionTargetMax'
          | 'media.discovery.maxSeedShelves'
          | 'media.discovery.maxGenreShelves'
          | 'media.discovery.maxActiveCollections'
          | 'media.discovery.maxBecauseYouWatchedSeeds'
          | 'media.discovery.maxCreditsSeeds'
          | 'media.discovery.maxBestInGenre'
          | 'media.discovery.maxCrossoverPairs'
          | 'media.thetvdb.rateLimitCapacity'
          | 'media.thetvdb.rateLimitRefillRate'
          | 'media.thetvdb.maxRetries'
          | 'media.tmdb.genreCacheTtlMs'
          | 'media.tmdb.imageMaxRetries'
          | 'media.tmdb.imageRetryDelayMs'
          | 'media.plex.rateLimitDelayMs'
          | 'media.plex.clientPageSize'
          | 'media.plex.friendsPageSize'
          | 'media.defaultLimit'
          | 'media.rotation.tmdbDefaultPages'
          | 'media.rotation.tmdbMaxPages'
          | 'media.rotation.tmdbMinVoteCount'
          | 'media.rotation.letterboxdMaxPages'
          | 'finance.aiCategorizer.model'
          | 'finance.aiCategorizer.maxTokens'
          | 'finance.ruleGen.model'
          | 'finance.ruleGen.maxTokens'
          | 'finance.defaultLimit'
          | 'inventory.defaultLimit'
          | 'inventory.searchDefaultLimit'
          | 'inventory.maxFileSizeBytes'
          | 'core.corrections.highConfidenceThreshold'
          | 'core.corrections.minPatternLength'
          | 'core.corrections.previewLimit'
          | 'core.corrections.previewHardLimit'
          | 'core.corrections.previewRulesFetchLimit'
          | 'core.search.showMoreLimit'
          | 'core.aiRetry.maxRetries'
          | 'core.aiRetry.baseDelayMs'
          | 'core.defaultLimit'
          | 'core.queue.syncConcurrency'
          | 'core.queue.embeddingsConcurrency'
          | 'core.queue.defaultConcurrency'
          | 'core.queue.completedRetention'
          | 'theme';
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          value: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.resetKey': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'plex_url'
          | 'plex_token'
          | 'plex_username'
          | 'plex_encryption_seed'
          | 'plex_client_identifier'
          | 'plex_movie_section_id'
          | 'plex_tv_section_id'
          | 'plex_scheduler_enabled'
          | 'plex_scheduler_interval_ms'
          | 'radarr_url'
          | 'radarr_api_key'
          | 'sonarr_url'
          | 'sonarr_api_key'
          | 'ai.model'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'cerebrum.query.maxSources'
          | 'cerebrum.query.relevanceThreshold'
          | 'cerebrum.query.tokenBudget'
          | 'cerebrum.emit.maxTokens'
          | 'cerebrum.emit.relevanceThreshold'
          | 'cerebrum.emit.maxSources'
          | 'cerebrum.emit.tokenBudget'
          | 'cerebrum.semantic.defaultLimit'
          | 'cerebrum.semantic.defaultThreshold'
          | 'cerebrum.semantic.queryCacheTtl'
          | 'cerebrum.hybrid.rrfK'
          | 'cerebrum.hybrid.defaultLimit'
          | 'cerebrum.hybrid.defaultThreshold'
          | 'cerebrum.context.tokenBudget'
          | 'cerebrum.classifier.confidenceThreshold'
          | 'cerebrum.entityExtractor.confidenceThreshold'
          | 'cerebrum.captureHotkey'
          | 'cerebrum.nudge.consolidationSimilarity'
          | 'cerebrum.nudge.consolidationMinCluster'
          | 'cerebrum.nudge.stalenessDays'
          | 'cerebrum.nudge.patternMinOccurrences'
          | 'cerebrum.nudge.maxPending'
          | 'cerebrum.nudge.cooldownHours'
          | 'cerebrum.engram.fallbackScope'
          | 'cerebrum.citation.excerptMaxLength'
          | 'cerebrum.plexus.healthIntervalMs'
          | 'cerebrum.plexus.healthTimeoutMs'
          | 'cerebrum.plexus.maxConsecutiveFailures'
          | 'cerebrum.thalamus.crossSourceIntervalMs'
          | 'cerebrum.mcp.queryMaxSources'
          | 'cerebrum.mcp.searchSnippetLength'
          | 'cerebrum.mcp.searchDefaultLimit'
          | 'cerebrum.glia.proposeMinApproved'
          | 'cerebrum.glia.proposeMaxRejectionRate'
          | 'cerebrum.glia.actReportMinDays'
          | 'cerebrum.glia.demotionRevertThreshold'
          | 'cerebrum.glia.demotionWindowDays'
          | 'ego.defaultModel'
          | 'ego.maxHistory'
          | 'ego.maxRetrieval'
          | 'ego.tokenBudget'
          | 'ego.relevanceThreshold'
          | 'ego.chat.maxTokens'
          | 'ego.chat.temperature'
          | 'ego.summary.maxTokens'
          | 'ego.summary.temperature'
          | 'media.comparisons.eloK'
          | 'media.comparisons.defaultScore'
          | 'media.comparisons.maxTierListMovies'
          | 'media.comparisons.stalenessThreshold'
          | 'media.comparisons.defaultLimit'
          | 'media.discovery.sessionTargetMin'
          | 'media.discovery.sessionTargetMax'
          | 'media.discovery.maxSeedShelves'
          | 'media.discovery.maxGenreShelves'
          | 'media.discovery.maxActiveCollections'
          | 'media.discovery.maxBecauseYouWatchedSeeds'
          | 'media.discovery.maxCreditsSeeds'
          | 'media.discovery.maxBestInGenre'
          | 'media.discovery.maxCrossoverPairs'
          | 'media.thetvdb.rateLimitCapacity'
          | 'media.thetvdb.rateLimitRefillRate'
          | 'media.thetvdb.maxRetries'
          | 'media.tmdb.genreCacheTtlMs'
          | 'media.tmdb.imageMaxRetries'
          | 'media.tmdb.imageRetryDelayMs'
          | 'media.plex.rateLimitDelayMs'
          | 'media.plex.clientPageSize'
          | 'media.plex.friendsPageSize'
          | 'media.defaultLimit'
          | 'media.rotation.tmdbDefaultPages'
          | 'media.rotation.tmdbMaxPages'
          | 'media.rotation.tmdbMinVoteCount'
          | 'media.rotation.letterboxdMaxPages'
          | 'finance.aiCategorizer.model'
          | 'finance.aiCategorizer.maxTokens'
          | 'finance.ruleGen.model'
          | 'finance.ruleGen.maxTokens'
          | 'finance.defaultLimit'
          | 'inventory.defaultLimit'
          | 'inventory.searchDefaultLimit'
          | 'inventory.maxFileSizeBytes'
          | 'core.corrections.highConfidenceThreshold'
          | 'core.corrections.minPatternLength'
          | 'core.corrections.previewLimit'
          | 'core.corrections.previewHardLimit'
          | 'core.corrections.previewRulesFetchLimit'
          | 'core.search.showMoreLimit'
          | 'core.aiRetry.maxRetries'
          | 'core.aiRetry.baseDelayMs'
          | 'core.defaultLimit'
          | 'core.queue.syncConcurrency'
          | 'core.queue.embeddingsConcurrency'
          | 'core.queue.defaultConcurrency'
          | 'core.queue.completedRetention'
          | 'theme';
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            };
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'shell.manifest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            apps: string[];
            overlays: string[];
          };
        };
      };
    };
  };
  'users.get': {
    parameters: {
      query: {
        uri: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              uri: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
}
