import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, expectTypeOf, it } from 'vitest';

import type { ListsContract } from '../manifest.js';
import type { ListItem } from '../types/list-item.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(HERE, '..', '..');
const GENERATED_PATH = resolve(PACKAGE_ROOT, 'src', 'manifest.generated.ts');
const AUTOGENERATED_HEADER = '// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.';

describe('ListsContract manifest type generation', () => {
  it('exposes ListItem on entities.listItem with byte-equal shape', () => {
    expectTypeOf<ListsContract['entities']['listItem']>().toEqualTypeOf<ListItem>();
  });

  it('pins pillar discriminant and exposes errors/router slots', () => {
    expectTypeOf<ListsContract['pillar']>().toEqualTypeOf<'lists'>();
    expectTypeOf<ListsContract['version']>().toEqualTypeOf<string>();
    expectTypeOf<ListsContract>().toHaveProperty('errors');
    expectTypeOf<ListsContract>().toHaveProperty('router');
  });

  it('emits the AUTOGENERATED header so hand-edits fail loudly', () => {
    const contents = readFileSync(GENERATED_PATH, 'utf8');
    expect(contents).toContain(AUTOGENERATED_HEADER);
  });

  it('regeneration is idempotent (no diff on a second run)', () => {
    const before = readFileSync(GENERATED_PATH, 'utf8');
    execFileSync('pnpm', ['--silent', 'run', 'generate:manifest'], {
      cwd: PACKAGE_ROOT,
      stdio: ['ignore', 'ignore', 'inherit'],
    });
    const after = readFileSync(GENERATED_PATH, 'utf8');
    expect(after).toBe(before);
  });
});
