// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body accepted by `POST /entities`. `type` defaults to `company`; the array
 * fields default to empty.
 */
export type CreateEntityBody = {
  abn?: string | null;
  aliases?: Array<string>;
  defaultTags?: Array<string>;
  defaultTransactionType?: string | null;
  name: string;
  notes?: string | null;
  type?: string | null;
};

/**
 * The wire shape served by every entities route. `notionId`, `ownerUri`, and
 * `ownerUriStaleAt` are deliberately NOT exposed (internal/integration
 * columns).
 */
export type Entity = {
  abn?: string | null;
  aliases: Array<string>;
  defaultTags: Array<string>;
  defaultTransactionType?: string | null;
  id: string;
  lastEditedTime: string;
  name: string;
  notes?: string | null;
  type: string;
};

/**
 * `GET /entities` response body.
 */
export type EntityListResponse = {
  data: Array<Entity>;
  pagination: PaginationMeta;
};

/**
 * Wire shape of one bulk-lookup entry.
 */
export type EntityLookup = {
  aliases: Array<string>;
  id: string;
  name: string;
};

/**
 * Create/update response body — the entity plus a human-readable message.
 */
export type EntityMutation = {
  data: Entity;
  message: string;
};

/**
 * `GET /entities/:id` response body.
 */
export type EntityResponse = {
  data: Entity;
};

/**
 * Error envelope returned by every fallible route. `code` carries the
 * originating error class name (e.g. `NotFoundError`) so clients can branch
 * without parsing `message`.
 */
export type ErrorBody = {
  code?: string | null;
  message: string;
};

/**
 * `GET /health` response body. Field-for-field identical to the TS pillar
 * health envelope: `ok`, `status`, `pillar`, `version`, `ts` (an RFC 3339 /
 * ISO 8601 UTC timestamp, matching the TS `new Date().toISOString()`). The
 * registry health probe parses this shape across every pillar.
 */
export type HealthResponse = {
  ok: boolean;
  pillar: string;
  status: string;
  ts: string;
  version: string;
};

/**
 * `POST /entities/lookup` body — reserved for a future field selector; an
 * empty body fetches the default match columns.
 */
export type LookupBody = {
  fields?: Array<string> | null;
};

/**
 * `POST /entities/lookup` response — the whole contact set's match columns in
 * one round-trip, plus the fetch instant for the caller's in-run cache.
 */
export type LookupResponse = {
  entities: Array<EntityLookup>;
  fetchedAt: string;
};

export type MatchType = 'exact' | 'prefix' | 'contains';

/**
 * Bare `{ message }` body returned by delete.
 */
export type MessageResponse = {
  message: string;
};

/**
 * Pagination envelope returned by every list endpoint. Mirrors core's
 * `PaginationMetaSchema`.
 */
export type PaginationMeta = {
  hasMore: boolean;
  limit: number;
  offset: number;
  total: number;
};

/**
 * One ranked search hit. `uri` is the canonical `pops:contacts/contact/<id>`.
 */
export type SearchHit = {
  data: SearchHitData;
  matchField: string;
  matchType: MatchType;
  score: number;
  uri: string;
};

export type SearchHitData = {
  aliases: Array<string>;
  name: string;
  type: string;
};

export type SearchQuery = {
  text: string;
};

/**
 * `POST /search` request body. `query.text` is the term; `context` is
 * accepted and ignored (parity with the orchestrator's wire shape).
 */
export type SearchRequest = {
  context?: unknown;
  query: SearchQuery;
};

/**
 * `POST /search` response body.
 */
export type SearchResponse = {
  hits: Array<SearchHit>;
};

/**
 * Body accepted by `PATCH /entities/:id`. Every field is optional; a present
 * field (even `null` for the nullable columns) is applied, an absent field is
 * left untouched. The nullable columns use `Option<Option<T>>` to tell
 * "absent" (outer `None` — leave the column alone) apart from "set to null"
 * (`Some(None)` — clear the column). serde collapses a JSON `null` into the
 * outer `None` by default, so those fields deserialize through
 * [`double_option`], which preserves the present-but-null case.
 */
export type UpdateEntityBody = {
  abn?: string | null;
  aliases?: Array<string> | null;
  defaultTags?: Array<string> | null;
  defaultTransactionType?: string | null;
  name?: string | null;
  notes?: string | null;
  type?: string | null;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type RootGetResponses = {
  /**
   * Pillar identity banner
   */
  200: string;
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type EntitiesListData = {
  body?: never;
  path?: never;
  query?: {
    search?: string | null;
    type?: string | null;
    limit?: number | null;
    offset?: number | null;
  };
  url: '/entities';
};

export type EntitiesListResponses = {
  /**
   * Paginated entity list
   */
  200: EntityListResponse;
};

export type EntitiesListResponse = EntitiesListResponses[keyof EntitiesListResponses];

export type EntitiesCreateData = {
  body: CreateEntityBody;
  path?: never;
  query?: never;
  url: '/entities';
};

export type EntitiesCreateErrors = {
  /**
   * Invalid body
   */
  400: ErrorBody;
  /**
   * Duplicate name
   */
  409: ErrorBody;
};

export type EntitiesCreateError = EntitiesCreateErrors[keyof EntitiesCreateErrors];

export type EntitiesCreateResponses = {
  /**
   * Created entity
   */
  201: EntityMutation;
};

export type EntitiesCreateResponse = EntitiesCreateResponses[keyof EntitiesCreateResponses];

export type EntitiesLookupData = {
  body: LookupBody;
  path?: never;
  query?: never;
  url: '/entities/lookup';
};

export type EntitiesLookupResponses = {
  /**
   * Bulk match columns
   */
  200: LookupResponse;
};

export type EntitiesLookupResponse = EntitiesLookupResponses[keyof EntitiesLookupResponses];

export type EntitiesDeleteData = {
  body?: never;
  path: {
    /**
     * Entity id
     */
    id: string;
  };
  query?: never;
  url: '/entities/{id}';
};

export type EntitiesDeleteErrors = {
  /**
   * No such entity
   */
  404: ErrorBody;
};

export type EntitiesDeleteError = EntitiesDeleteErrors[keyof EntitiesDeleteErrors];

export type EntitiesDeleteResponses = {
  /**
   * Deleted
   */
  200: MessageResponse;
};

export type EntitiesDeleteResponse = EntitiesDeleteResponses[keyof EntitiesDeleteResponses];

export type EntitiesGetData = {
  body?: never;
  path: {
    /**
     * Entity id
     */
    id: string;
  };
  query?: never;
  url: '/entities/{id}';
};

export type EntitiesGetErrors = {
  /**
   * No such entity
   */
  404: ErrorBody;
};

export type EntitiesGetError = EntitiesGetErrors[keyof EntitiesGetErrors];

export type EntitiesGetResponses = {
  /**
   * The entity
   */
  200: EntityResponse;
};

export type EntitiesGetResponse = EntitiesGetResponses[keyof EntitiesGetResponses];

export type EntitiesUpdateData = {
  body: UpdateEntityBody;
  path: {
    /**
     * Entity id
     */
    id: string;
  };
  query?: never;
  url: '/entities/{id}';
};

export type EntitiesUpdateErrors = {
  /**
   * No such entity
   */
  404: ErrorBody;
  /**
   * Duplicate name
   */
  409: ErrorBody;
};

export type EntitiesUpdateError = EntitiesUpdateErrors[keyof EntitiesUpdateErrors];

export type EntitiesUpdateResponses = {
  /**
   * Updated entity
   */
  200: EntityMutation;
};

export type EntitiesUpdateResponse = EntitiesUpdateResponses[keyof EntitiesUpdateResponses];

export type HealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthGetResponses = {
  /**
   * Pillar is live
   */
  200: HealthResponse;
};

export type HealthGetResponse = HealthGetResponses[keyof HealthGetResponses];

export type SearchSearchData = {
  body: SearchRequest;
  path?: never;
  query?: never;
  url: '/search';
};

export type SearchSearchResponses = {
  /**
   * Ranked contact hits
   */
  200: SearchResponse;
};

export type SearchSearchResponse = SearchSearchResponses[keyof SearchSearchResponses];
