/**
 * Structural snapshot of the inventory pillar's public surface. Type now
 * lives in `manifest.generated.ts` and is regenerated by
 * `pnpm -F @pops/inventory-contract generate:manifest` (Theme 13 PRD-155).
 * This file remains the stable import path (`@pops/inventory-contract/manifest`)
 * so downstream consumers don't move with the generator output.
 */
export type { InventoryContract } from './manifest.generated.js';
