import type { InventoryError } from './errors.js';
import type { InventoryRouter } from './router.js';
// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.
// Regenerated by `pnpm -F @pops/inventory-contract generate:manifest`.
// Source version pinned at generation time: 0.1.0
import type { Connection } from './types/connection.js';
import type { Item } from './types/item.js';
import type { Location } from './types/location.js';
import type { Warranty } from './types/warranty.js';

export interface InventoryContract {
  readonly pillar: 'inventory';
  readonly version: string;
  readonly entities: {
    readonly connection: Connection;
    readonly item: Item;
    readonly location: Location;
    readonly warranty: Warranty;
  };
  readonly errors: InventoryError;
  readonly router: InventoryRouter;
}
