// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type FeaturesListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/features';
};

export type FeaturesListErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type FeaturesListError = FeaturesListErrors[keyof FeaturesListErrors];

export type FeaturesListResponses = {
  /**
   * 200
   */
  200: {
    features: Array<{
      capabilityMissing?: boolean;
      configureLink?: string;
      credentials: Array<{
        envVar?: string;
        key: string;
        source: 'database' | 'environment' | 'missing';
      }>;
      default: boolean;
      deprecated?: boolean;
      description?: string;
      enabled: boolean;
      key: string;
      label: string;
      manifestId: string;
      preview?: boolean;
      scope: 'system' | 'user' | 'capability';
      state: 'enabled' | 'disabled' | 'unavailable';
      userOverride?: boolean;
    }>;
  };
};

export type FeaturesListResponse = FeaturesListResponses[keyof FeaturesListResponses];

export type FeaturesGetManifestsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/features/manifests';
};

export type FeaturesGetManifestsErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type FeaturesGetManifestsError =
  FeaturesGetManifestsErrors[keyof FeaturesGetManifestsErrors];

export type FeaturesGetManifestsResponses = {
  /**
   * 200
   */
  200: {
    manifests: Array<{
      features: Array<{
        configureLink?: string;
        default: boolean;
        deprecated?: boolean;
        description?: string;
        key: string;
        label: string;
        preview?: boolean;
        requires?: Array<string>;
        requiresEnv?: Array<string>;
        scope: 'system' | 'user' | 'capability';
        settingKey?: string;
      }>;
      icon?: string;
      id: string;
      order: number;
      title: string;
    }>;
  };
};

export type FeaturesGetManifestsResponse =
  FeaturesGetManifestsResponses[keyof FeaturesGetManifestsResponses];

export type FeaturesIsEnabledData = {
  body?: never;
  path: {
    key: string;
  };
  query?: never;
  url: '/features/{key}/enabled';
};

export type FeaturesIsEnabledErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type FeaturesIsEnabledError = FeaturesIsEnabledErrors[keyof FeaturesIsEnabledErrors];

export type FeaturesIsEnabledResponses = {
  /**
   * 200
   */
  200: {
    enabled: boolean;
  };
};

export type FeaturesIsEnabledResponse =
  FeaturesIsEnabledResponses[keyof FeaturesIsEnabledResponses];

export type FeaturesSetEnabledData = {
  /**
   * Body
   */
  body?: {
    enabled: boolean;
  };
  path: {
    key: string;
  };
  query?: never;
  url: '/features/{key}/enabled';
};

export type FeaturesSetEnabledErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type FeaturesSetEnabledError = FeaturesSetEnabledErrors[keyof FeaturesSetEnabledErrors];

export type FeaturesSetEnabledResponses = {
  /**
   * 200
   */
  200: {
    enabled: boolean;
  };
};

export type FeaturesSetEnabledResponse =
  FeaturesSetEnabledResponses[keyof FeaturesSetEnabledResponses];

export type FeaturesClearUserPreferenceData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path: {
    key: string;
  };
  query?: never;
  url: '/features/{key}/preference';
};

export type FeaturesClearUserPreferenceErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type FeaturesClearUserPreferenceError =
  FeaturesClearUserPreferenceErrors[keyof FeaturesClearUserPreferenceErrors];

export type FeaturesClearUserPreferenceResponses = {
  /**
   * 200
   */
  200: {
    cleared: boolean;
  };
};

export type FeaturesClearUserPreferenceResponse =
  FeaturesClearUserPreferenceResponses[keyof FeaturesClearUserPreferenceResponses];

export type FeaturesSetUserPreferenceData = {
  /**
   * Body
   */
  body?: {
    enabled: boolean;
  };
  path: {
    key: string;
  };
  query?: never;
  url: '/features/{key}/preference';
};

export type FeaturesSetUserPreferenceErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type FeaturesSetUserPreferenceError =
  FeaturesSetUserPreferenceErrors[keyof FeaturesSetUserPreferenceErrors];

export type FeaturesSetUserPreferenceResponses = {
  /**
   * 200
   */
  200: {
    enabled: boolean;
  };
};

export type FeaturesSetUserPreferenceResponse =
  FeaturesSetUserPreferenceResponses[keyof FeaturesSetUserPreferenceResponses];

export type ServiceAccountsListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/service-accounts';
};

export type ServiceAccountsListErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type ServiceAccountsListError = ServiceAccountsListErrors[keyof ServiceAccountsListErrors];

export type ServiceAccountsListResponses = {
  /**
   * 200
   */
  200: Array<{
    createdAt: string;
    createdBy: string | null;
    id: string;
    keyPrefix: string;
    lastUsedAt: string | null;
    name: string;
    revokedAt: string | null;
    scopes: Array<string>;
  }>;
};

export type ServiceAccountsListResponse =
  ServiceAccountsListResponses[keyof ServiceAccountsListResponses];

export type ServiceAccountsCreateData = {
  /**
   * Body
   */
  body?: {
    name: string;
    scopes: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/service-accounts';
};

export type ServiceAccountsCreateErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type ServiceAccountsCreateError =
  ServiceAccountsCreateErrors[keyof ServiceAccountsCreateErrors];

export type ServiceAccountsCreateResponses = {
  /**
   * 201
   */
  201: {
    createdAt: string;
    createdBy: string | null;
    id: string;
    keyPrefix: string;
    lastUsedAt: string | null;
    name: string;
    plaintextKey: string;
    revokedAt: string | null;
    scopes: Array<string>;
  };
};

export type ServiceAccountsCreateResponse =
  ServiceAccountsCreateResponses[keyof ServiceAccountsCreateResponses];

export type ServiceAccountsRevokeData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/service-accounts/{id}/revoke';
};

export type ServiceAccountsRevokeErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type ServiceAccountsRevokeError =
  ServiceAccountsRevokeErrors[keyof ServiceAccountsRevokeErrors];

export type ServiceAccountsRevokeResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
  };
};

export type ServiceAccountsRevokeResponse =
  ServiceAccountsRevokeResponses[keyof ServiceAccountsRevokeResponses];

export type SettingsListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/settings';
};

export type SettingsListErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsListError = SettingsListErrors[keyof SettingsListErrors];

export type SettingsListResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      key: string;
      value: string;
    }>;
  };
};

export type SettingsListResponse = SettingsListResponses[keyof SettingsListResponses];

export type SettingsAggregateData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/settings/aggregate';
};

export type SettingsAggregateErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsAggregateError = SettingsAggregateErrors[keyof SettingsAggregateErrors];

export type SettingsAggregateResponses = {
  /**
   * 200
   */
  200: {
    fetchedAt: string;
    pillars: Array<{
      error?: 'unreachable' | 'unauthorized';
      pillarId: string;
      settings: Array<{
        key: string;
        value: string;
      }>;
    }>;
  };
};

export type SettingsAggregateResponse =
  SettingsAggregateResponses[keyof SettingsAggregateResponses];

export type SettingsGetManyData = {
  /**
   * Body
   */
  body?: {
    keys: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/settings/get-many';
};

export type SettingsGetManyErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsGetManyError = SettingsGetManyErrors[keyof SettingsGetManyErrors];

export type SettingsGetManyResponses = {
  /**
   * 200
   */
  200: {
    settings: {
      [key: string]: string;
    };
  };
};

export type SettingsGetManyResponse = SettingsGetManyResponses[keyof SettingsGetManyResponses];

export type SettingsResetData = {
  /**
   * Body
   */
  body?: {
    keys?: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/settings/reset';
};

export type SettingsResetErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsResetError = SettingsResetErrors[keyof SettingsResetErrors];

export type SettingsResetResponses = {
  /**
   * 200
   */
  200: {
    reset: Array<string>;
    settings: {
      [key: string]: string;
    };
  };
};

export type SettingsResetResponse = SettingsResetResponses[keyof SettingsResetResponses];

export type SettingsSetManyData = {
  /**
   * Body
   */
  body?: {
    entries: Array<{
      key: string;
      value: string;
    }>;
  };
  path?: never;
  query?: never;
  url: '/settings/set-many';
};

export type SettingsSetManyErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsSetManyError = SettingsSetManyErrors[keyof SettingsSetManyErrors];

export type SettingsSetManyResponses = {
  /**
   * 200
   */
  200: {
    settings: {
      [key: string]: string;
    };
  };
};

export type SettingsSetManyResponse = SettingsSetManyResponses[keyof SettingsSetManyResponses];

export type SettingsDeleteData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path: {
    key:
      | 'core.corrections.highConfidenceThreshold'
      | 'core.corrections.minPatternLength'
      | 'core.corrections.previewLimit'
      | 'core.corrections.previewHardLimit'
      | 'core.corrections.previewRulesFetchLimit'
      | 'core.search.showMoreLimit'
      | 'core.aiRetry.maxRetries'
      | 'core.aiRetry.baseDelayMs'
      | 'core.defaultLimit'
      | 'core.queue.syncConcurrency'
      | 'core.queue.embeddingsConcurrency'
      | 'core.queue.defaultConcurrency'
      | 'core.queue.completedRetention';
  };
  query?: never;
  url: '/settings/{key}';
};

export type SettingsDeleteErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsDeleteError = SettingsDeleteErrors[keyof SettingsDeleteErrors];

export type SettingsDeleteResponses = {
  /**
   * 200
   */
  200: {
    message: string;
  };
};

export type SettingsDeleteResponse = SettingsDeleteResponses[keyof SettingsDeleteResponses];

export type SettingsGetData = {
  body?: never;
  path: {
    key:
      | 'core.corrections.highConfidenceThreshold'
      | 'core.corrections.minPatternLength'
      | 'core.corrections.previewLimit'
      | 'core.corrections.previewHardLimit'
      | 'core.corrections.previewRulesFetchLimit'
      | 'core.search.showMoreLimit'
      | 'core.aiRetry.maxRetries'
      | 'core.aiRetry.baseDelayMs'
      | 'core.defaultLimit'
      | 'core.queue.syncConcurrency'
      | 'core.queue.embeddingsConcurrency'
      | 'core.queue.defaultConcurrency'
      | 'core.queue.completedRetention';
  };
  query?: never;
  url: '/settings/{key}';
};

export type SettingsGetErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsGetError = SettingsGetErrors[keyof SettingsGetErrors];

export type SettingsGetResponses = {
  /**
   * 200
   */
  200: {
    data: {
      key: string;
      value: string;
    } | null;
  };
};

export type SettingsGetResponse = SettingsGetResponses[keyof SettingsGetResponses];

export type SettingsSetData = {
  /**
   * Body
   */
  body?: {
    value: string;
  };
  path: {
    key:
      | 'core.corrections.highConfidenceThreshold'
      | 'core.corrections.minPatternLength'
      | 'core.corrections.previewLimit'
      | 'core.corrections.previewHardLimit'
      | 'core.corrections.previewRulesFetchLimit'
      | 'core.search.showMoreLimit'
      | 'core.aiRetry.maxRetries'
      | 'core.aiRetry.baseDelayMs'
      | 'core.defaultLimit'
      | 'core.queue.syncConcurrency'
      | 'core.queue.embeddingsConcurrency'
      | 'core.queue.defaultConcurrency'
      | 'core.queue.completedRetention';
  };
  query?: never;
  url: '/settings/{key}';
};

export type SettingsSetErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsSetError = SettingsSetErrors[keyof SettingsSetErrors];

export type SettingsSetResponses = {
  /**
   * 200
   */
  200: {
    data: {
      key: string;
      value: string;
    };
    message: string;
  };
};

export type SettingsSetResponse = SettingsSetResponses[keyof SettingsSetResponses];

export type SettingsEnsureData = {
  /**
   * Body
   */
  body?: {
    value: string;
  };
  path: {
    key:
      | 'core.corrections.highConfidenceThreshold'
      | 'core.corrections.minPatternLength'
      | 'core.corrections.previewLimit'
      | 'core.corrections.previewHardLimit'
      | 'core.corrections.previewRulesFetchLimit'
      | 'core.search.showMoreLimit'
      | 'core.aiRetry.maxRetries'
      | 'core.aiRetry.baseDelayMs'
      | 'core.defaultLimit'
      | 'core.queue.syncConcurrency'
      | 'core.queue.embeddingsConcurrency'
      | 'core.queue.defaultConcurrency'
      | 'core.queue.completedRetention';
  };
  query?: never;
  url: '/settings/{key}/ensure';
};

export type SettingsEnsureErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsEnsureError = SettingsEnsureErrors[keyof SettingsEnsureErrors];

export type SettingsEnsureResponses = {
  /**
   * 200
   */
  200: {
    data: {
      key: string;
      value: string;
    };
  };
};

export type SettingsEnsureResponse = SettingsEnsureResponses[keyof SettingsEnsureResponses];

export type SettingsResetKeyData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path: {
    key:
      | 'core.corrections.highConfidenceThreshold'
      | 'core.corrections.minPatternLength'
      | 'core.corrections.previewLimit'
      | 'core.corrections.previewHardLimit'
      | 'core.corrections.previewRulesFetchLimit'
      | 'core.search.showMoreLimit'
      | 'core.aiRetry.maxRetries'
      | 'core.aiRetry.baseDelayMs'
      | 'core.defaultLimit'
      | 'core.queue.syncConcurrency'
      | 'core.queue.embeddingsConcurrency'
      | 'core.queue.defaultConcurrency'
      | 'core.queue.completedRetention';
  };
  query?: never;
  url: '/settings/{key}/reset';
};

export type SettingsResetKeyErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 401
   */
  401: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SettingsResetKeyError = SettingsResetKeyErrors[keyof SettingsResetKeyErrors];

export type SettingsResetKeyResponses = {
  /**
   * 200
   */
  200: {
    data: {
      key: string;
      value: string;
    };
    message: string;
  };
};

export type SettingsResetKeyResponse = SettingsResetKeyResponses[keyof SettingsResetKeyResponses];

export type ShellManifestData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/shell/manifest';
};

export type ShellManifestResponses = {
  /**
   * 200
   */
  200: {
    apps: Array<string>;
    overlays: Array<string>;
  };
};

export type ShellManifestResponse = ShellManifestResponses[keyof ShellManifestResponses];

export type UsersGetData = {
  body?: never;
  path?: never;
  query: {
    uri: string;
  };
  url: '/users';
};

export type UsersGetErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type UsersGetError = UsersGetErrors[keyof UsersGetErrors];

export type UsersGetResponses = {
  /**
   * 200
   */
  200: {
    data: {
      uri: string;
    };
  };
};

export type UsersGetResponse = UsersGetResponses[keyof UsersGetResponses];
