---
github_runner_version: '2.333.1'
github_runner_user: '{{ pops_user }}'
github_runner_dir: '/opt/github-runner'
github_repo_url: 'https://github.com/knoxio/pops'
github_runner_labels: 'self-hosted,linux,x64'
github_runner_name: '{{ ansible_hostname }}'
github_runner_service_name: >-
  actions.runner.{{ github_repo_url | replace('https://github.com/', '') | replace('/', '-') }}.{{ github_runner_name }}.service
github_runner_pat: '{{ vault_github_runner_pat }}'
