/**
 * AUTOGENERATED by scripts/generate-api-types.ts via openapi-typescript.
 * Do not edit by hand — regenerate via `pnpm -F @pops/lists generate:api-types`.
 * Drift check in lists-quality.yml fails on hand-edits.
 */
export interface paths {
  '/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search items across lists (filters: kind, listId, includeArchived, labelContains, notesContains) */
    get: operations['items.search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/items/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove an item (idempotent) */
    delete: operations['items.remove'];
    options?: never;
    head?: never;
    /** Patch a list item */
    patch: operations['items.update'];
    trace?: never;
  };
  '/items/{id}/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark an item as checked */
    post: operations['items.check'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/items/{id}/uncheck': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark an item as unchecked */
    post: operations['items.uncheck'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Aggregate list view for the lists index page */
    get: operations['list.listAggregate'];
    put?: never;
    /** Create a list */
    post: operations['list.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single list header plus its items in one round-trip */
    get: operations['list.get'];
    put?: never;
    post?: never;
    /** Hard-delete a list (cascades items) */
    delete: operations['list.delete'];
    options?: never;
    head?: never;
    /** Patch a list header (name and/or kind) */
    patch: operations['list.update'];
    trace?: never;
  };
  '/lists/{id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive a list */
    post: operations['list.archive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{id}/unarchive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unarchive a list */
    post: operations['list.unarchive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{listId}/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add an item to a list */
    post: operations['items.add'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{listId}/items/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add many items in one transaction */
    post: operations['items.bulkAdd'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{listId}/items/checked': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Hard-delete every checked item in a list */
    delete: operations['items.removeChecked'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{listId}/items/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder items within a list */
    post: operations['items.reorder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{listId}/items/uncheck-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Uncheck every checked item in a list */
    post: operations['items.uncheckAll'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lists/{listId}/items/upsert-by-ref': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Atomic merge-or-insert by (refKind, refId). onConflict picks merge-additive / replace / skip */
    post: operations['items.upsertByRef'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'items.search': {
    parameters: {
      query?: {
        kind?: 'shopping' | 'packing' | 'todo' | 'generic';
        listId?: number;
        includeArchived?: boolean;
        labelContains?: string;
        notesContains?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              checked: number;
              checkedAt: string | null;
              createdAt: string;
              dueAt: string | null;
              id: number;
              label: string;
              listId: number;
              notes: string | null;
              position: number;
              qty: number | null;
              refId: number | null;
              /** @enum {string} */
              refKind: 'free' | 'ingredient' | 'variant' | 'recipe' | 'custom';
              unit: string | null;
            }[];
          };
        };
      };
    };
  };
  'items.remove': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
    };
  };
  'items.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          label?: string;
          notes?: string | null;
          qty?: number | null;
          unit?: string | null;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'items.check': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            checkedAt: string;
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'items.uncheck': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'list.listAggregate': {
    parameters: {
      query?: {
        kinds?: ('shopping' | 'packing' | 'todo' | 'generic')[];
        includeArchived?: boolean;
        sort?: 'updated' | 'name' | 'created';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              archivedAt: string | null;
              id: number;
              itemCount: number;
              /** @enum {string} */
              kind: 'shopping' | 'packing' | 'todo' | 'generic';
              lastUpdatedAt: string;
              name: string;
              ownerApp: string;
              uncheckedCount: number;
            }[];
          };
        };
      };
    };
  };
  'list.create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          /** @enum {string} */
          kind: 'shopping' | 'packing' | 'todo' | 'generic';
          name: string;
          ownerApp?: string;
        };
      };
    };
    responses: {
      /** @description 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'list.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              checked: number;
              checkedAt: string | null;
              createdAt: string;
              dueAt: string | null;
              id: number;
              label: string;
              listId: number;
              notes: string | null;
              position: number;
              qty: number | null;
              refId: number | null;
              /** @enum {string} */
              refKind: 'free' | 'ingredient' | 'variant' | 'recipe' | 'custom';
              unit: string | null;
            }[];
            list: {
              archivedAt: string | null;
              createdAt: string;
              id: number;
              /** @enum {string} */
              kind: 'shopping' | 'packing' | 'todo' | 'generic';
              name: string;
              ownerApp: string;
            };
          } | null;
        };
      };
    };
  };
  'list.delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'list.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          /** @enum {string} */
          kind?: 'shopping' | 'packing' | 'todo' | 'generic';
          name?: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                /** @enum {boolean} */
                ok: true;
              }
            | {
                /** @enum {boolean} */
                ok: false;
                /** @enum {string} */
                reason: 'NotFound';
              };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'list.archive': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'list.unarchive': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'items.add': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listId: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          label: string;
          notes?: string | null;
          position?: number;
          qty?: number | null;
          refId?: number | null;
          /** @enum {string} */
          refKind?: 'free' | 'ingredient' | 'variant' | 'recipe' | 'custom';
          unit?: string | null;
        };
      };
    };
    responses: {
      /** @description 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            position: number;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'items.bulkAdd': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listId: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          items: {
            label: string;
            notes?: string | null;
            position?: number;
            qty?: number | null;
            refId?: number | null;
            /** @enum {string} */
            refKind?: 'free' | 'ingredient' | 'variant' | 'recipe' | 'custom';
            unit?: string | null;
          }[];
        };
      };
    };
    responses: {
      /** @description 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            addedIds: number[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'items.removeChecked': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listId: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
            removedCount: number;
          };
        };
      };
    };
  };
  'items.reorder': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listId: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          orderedIds: number[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                /** @enum {boolean} */
                ok: true;
              }
            | {
                /** @enum {boolean} */
                ok: false;
                /** @enum {string} */
                reason: 'BadIds';
              };
        };
      };
    };
  };
  'items.uncheckAll': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listId: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count: number;
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
    };
  };
  'items.upsertByRef': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listId: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          label: string;
          notes?: string | null;
          /** @enum {string} */
          onConflict?: 'merge-additive' | 'replace' | 'skip';
          qty?: number | null;
          refId: number;
          /** @enum {string} */
          refKind: 'ingredient' | 'variant' | 'recipe' | 'custom';
          unit?: string | null;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                itemId: number;
                /** @enum {string} */
                outcome: 'inserted';
                position: number;
              }
            | {
                itemId: number;
                /** @enum {string} */
                outcome: 'merged';
              }
            | {
                itemId: number;
                /** @enum {string} */
                outcome: 'skipped';
              };
        };
      };
      /** @description 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                itemId: number;
                /** @enum {string} */
                outcome: 'inserted';
                position: number;
              }
            | {
                itemId: number;
                /** @enum {string} */
                outcome: 'merged';
              }
            | {
                itemId: number;
                /** @enum {string} */
                outcome: 'skipped';
              };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
}
