/**
 * AUTOGENERATED by scripts/generate-api-types.ts via openapi-typescript.
 * Do not edit by hand — regenerate via `pnpm -F @pops/cerebrum generate:api-types`.
 */
export interface paths {
  '/templates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the available engram templates (bodies stripped). */
    get: operations['templates.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/templates/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single engram template by name, including its body. */
    get: operations['templates.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'templates.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            templates: {
              custom_fields?: {
                [key: string]: {
                  description: string;
                  /** @enum {string} */
                  type: 'string' | 'number' | 'boolean' | 'string[]' | 'number[]' | 'boolean[]';
                };
              };
              default_scopes?: string[];
              description: string;
              name: string;
              required_fields?: string[];
              suggested_sections?: string[];
            }[];
          };
        };
      };
    };
  };
  'templates.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            template: {
              body: string;
              custom_fields?: {
                [key: string]: {
                  description: string;
                  /** @enum {string} */
                  type: 'string' | 'number' | 'boolean' | 'string[]' | 'number[]' | 'boolean[]';
                };
              };
              default_scopes?: string[];
              description: string;
              name: string;
              required_fields?: string[];
              suggested_sections?: string[];
            };
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
}
