/**
 * AUTOGENERATED by scripts/generate-api-types.ts via openapi-typescript.
 * Do not edit by hand — regenerate via `pnpm -F @pops/cerebrum generate:api-types`.
 */
export interface paths {
  '/engrams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an engram (optionally scaffolded from a template). */
    post: operations['engrams.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/engrams/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** List engrams matching the supplied filters, with a total count. */
    post: operations['engrams.list'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/engrams/{engramId}/scopes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add scopes to an engram (merged with its existing scopes). */
    post: operations['scopes.assign'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/engrams/{engramId}/scopes/remove': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Remove scopes from an engram (rejects removing the last scope). */
    post: operations['scopes.remove'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/engrams/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an engram and its Markdown body. */
    get: operations['engrams.get'];
    put?: never;
    post?: never;
    /** Archive an engram (soft delete — moves the file under .archive/). */
    delete: operations['engrams.delete'];
    options?: never;
    head?: never;
    /** Update an engram (title/body/scopes/tags/status/template). */
    patch: operations['engrams.update'];
    trace?: never;
  };
  '/engrams/{sourceId}/links': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a bidirectional link from one engram to another. */
    post: operations['engrams.link'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/engrams/{sourceId}/links/{targetId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove the link between two engrams. */
    delete: operations['engrams.unlink'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plexus/adapters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List every registered plexus adapter. */
    get: operations['plexus.adapters.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plexus/adapters/{adapterId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single plexus adapter by id. */
    get: operations['plexus.adapters.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plexus/adapters/{adapterId}/filters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the ingestion filters for an adapter. */
    get: operations['plexus.filters.list'];
    put?: never;
    /** Atomically replace the ingestion filters for an adapter. */
    post: operations['plexus.filters.set'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plexus/adapters/{adapterId}/health-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run an on-demand health check against an adapter. */
    post: operations['plexus.adapters.healthCheck'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plexus/adapters/{adapterId}/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger a manual ingestion cycle for an adapter. */
    post: operations['plexus.adapters.sync'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plexus/adapters/{adapterId}/unregister': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Shut down and remove an adapter. */
    post: operations['plexus.adapters.unregister'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reflex': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List reflexes enriched with runtime status. */
    get: operations['reflex.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reflex/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Query the append-only reflex execution log (filtered + paginated). */
    post: operations['reflex.history'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reflex/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single reflex with its recent execution history. */
    get: operations['reflex.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reflex/{name}/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disable a reflex (rewrites the TOML config). */
    post: operations['reflex.disable'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reflex/{name}/enable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enable a reflex (rewrites the TOML config). */
    post: operations['reflex.enable'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reflex/{name}/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dry-run a reflex, logging a completed test execution. */
    post: operations['reflex.test'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scopes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List known scopes with engram counts, optionally filtered by prefix. */
    get: operations['scopes.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scopes/filter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Return engrams matching scope prefixes (secret-scoped excluded by default). */
    post: operations['scopes.filter'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scopes/reclassify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk prefix-rename a scope across every matching engram (atomic). */
    post: operations['scopes.reclassify'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scopes/reconcile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reconcile user-suggested scopes against the known vocabulary. */
    post: operations['scopes.reconcile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scopes/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate a single scope string; returns structured errors on failure. */
    post: operations['scopes.validate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List known tags ranked by usage count, optionally filtered by prefix. */
    get: operations['tags.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/templates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the available engram templates (bodies stripped). */
    get: operations['templates.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/templates/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single engram template by name, including its body. */
    get: operations['templates.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'engrams.create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          body?: string;
          customFields?: {
            [key: string]: unknown;
          };
          links?: string[];
          scopes?: string[];
          source?: string;
          tags?: string[];
          template?: string;
          title: string;
          type: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            engram: {
              contentHash: string;
              created: string;
              customFields: {
                [key: string]: unknown;
              };
              filePath: string;
              id: string;
              links: string[];
              modified: string;
              scopes: string[];
              source: string;
              /** @enum {string} */
              status: 'active' | 'archived' | 'consolidated' | 'stale';
              tags: string[];
              template: string | null;
              title: string;
              type: string;
              wordCount: number;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'engrams.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          ids?: string[];
          limit?: number;
          offset?: number;
          scopes?: string[];
          search?: string;
          sort?: {
            /** @enum {string} */
            direction: 'asc' | 'desc';
            /** @enum {string} */
            field: 'created_at' | 'modified_at' | 'title';
          };
          /** @enum {string} */
          status?: 'active' | 'archived' | 'consolidated' | 'stale';
          tags?: string[];
          type?: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            engrams: {
              contentHash: string;
              created: string;
              customFields: {
                [key: string]: unknown;
              };
              filePath: string;
              id: string;
              links: string[];
              modified: string;
              scopes: string[];
              source: string;
              /** @enum {string} */
              status: 'active' | 'archived' | 'consolidated' | 'stale';
              tags: string[];
              template: string | null;
              title: string;
              type: string;
              wordCount: number;
            }[];
            total: number;
          };
        };
      };
    };
  };
  'scopes.assign': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        engramId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          scopes: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            engram: {
              contentHash: string;
              created: string;
              customFields: {
                [key: string]: unknown;
              };
              filePath: string;
              id: string;
              links: string[];
              modified: string;
              scopes: string[];
              source: string;
              /** @enum {string} */
              status: 'active' | 'archived' | 'consolidated' | 'stale';
              tags: string[];
              template: string | null;
              title: string;
              type: string;
              wordCount: number;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'scopes.remove': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        engramId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          scopes: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            engram: {
              contentHash: string;
              created: string;
              customFields: {
                [key: string]: unknown;
              };
              filePath: string;
              id: string;
              links: string[];
              modified: string;
              scopes: string[];
              source: string;
              /** @enum {string} */
              status: 'active' | 'archived' | 'consolidated' | 'stale';
              tags: string[];
              template: string | null;
              title: string;
              type: string;
              wordCount: number;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'engrams.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            body: string;
            engram: {
              contentHash: string;
              created: string;
              customFields: {
                [key: string]: unknown;
              };
              filePath: string;
              id: string;
              links: string[];
              modified: string;
              scopes: string[];
              source: string;
              /** @enum {string} */
              status: 'active' | 'archived' | 'consolidated' | 'stale';
              tags: string[];
              template: string | null;
              title: string;
              type: string;
              wordCount: number;
            };
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'engrams.delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            success: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'engrams.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          body?: string;
          customFields?: {
            [key: string]: unknown;
          };
          scopes?: string[];
          /** @enum {string} */
          status?: 'active' | 'archived' | 'consolidated' | 'stale';
          tags?: string[];
          template?: string;
          title?: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            engram: {
              contentHash: string;
              created: string;
              customFields: {
                [key: string]: unknown;
              };
              filePath: string;
              id: string;
              links: string[];
              modified: string;
              scopes: string[];
              source: string;
              /** @enum {string} */
              status: 'active' | 'archived' | 'consolidated' | 'stale';
              tags: string[];
              template: string | null;
              title: string;
              type: string;
              wordCount: number;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'engrams.link': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sourceId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          targetId: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            success: true;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'engrams.unlink': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sourceId: string;
        targetId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            success: true;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'plexus.adapters.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            adapters: {
              config: {
                [key: string]: unknown;
              } | null;
              createdAt: string;
              emittedCount: number;
              id: string;
              ingestedCount: number;
              lastError: string | null;
              lastHealth: string | null;
              name: string;
              /** @enum {string} */
              status: 'registered' | 'initializing' | 'healthy' | 'degraded' | 'error' | 'shutdown';
              updatedAt: string;
            }[];
          };
        };
      };
    };
  };
  'plexus.adapters.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adapterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            adapter: {
              config: {
                [key: string]: unknown;
              } | null;
              createdAt: string;
              emittedCount: number;
              id: string;
              ingestedCount: number;
              lastError: string | null;
              lastHealth: string | null;
              name: string;
              /** @enum {string} */
              status: 'registered' | 'initializing' | 'healthy' | 'degraded' | 'error' | 'shutdown';
              updatedAt: string;
            };
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'plexus.filters.list': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adapterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            filters: {
              adapterId: string;
              enabled: boolean;
              field: string;
              /** @enum {string} */
              filterType: 'include' | 'exclude';
              id: string;
              pattern: string;
            }[];
          };
        };
      };
    };
  };
  'plexus.filters.set': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adapterId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          filters: {
            enabled?: boolean;
            field: string;
            /** @enum {string} */
            filterType: 'include' | 'exclude';
            pattern: string;
          }[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            filters: {
              adapterId: string;
              enabled: boolean;
              field: string;
              /** @enum {string} */
              filterType: 'include' | 'exclude';
              id: string;
              pattern: string;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'plexus.adapters.healthCheck': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adapterId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error?: string;
            lastCheck: string;
            /** @enum {string} */
            status: 'registered' | 'initializing' | 'healthy' | 'degraded' | 'error' | 'shutdown';
          };
        };
      };
    };
  };
  'plexus.adapters.sync': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adapterId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            filtered: number;
            ingested: number;
          };
        };
      };
    };
  };
  'plexus.adapters.unregister': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adapterId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
          };
        };
      };
    };
  };
  'reflex.list': {
    parameters: {
      query?: {
        timezone?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            reflexes: {
              action: {
                scopes?: string[];
                target?: string;
                template?: string;
                /** @enum {string} */
                type: 'ingest' | 'emit' | 'glia';
                verb: string;
              };
              description: string;
              enabled: boolean;
              executionCount: number;
              lastExecutionAt: string | null;
              name: string;
              nextFireTime: string | null;
              trigger:
                | {
                    conditions?: {
                      scopes?: string[];
                      source?: string;
                      type?: string;
                    };
                    /** @enum {string} */
                    event:
                      | 'engram.created'
                      | 'engram.modified'
                      | 'engram.archived'
                      | 'engram.linked';
                    /** @enum {string} */
                    type: 'event';
                  }
                | {
                    /** @enum {string} */
                    metric: 'similar_count' | 'staleness_max' | 'topic_frequency';
                    scopes?: string[];
                    /** @enum {string} */
                    type: 'threshold';
                    value: number;
                  }
                | {
                    cron: string;
                    /** @enum {string} */
                    type: 'schedule';
                  };
            }[];
          };
        };
      };
    };
  };
  'reflex.history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          limit?: number;
          name?: string;
          offset?: number;
          /** @enum {string} */
          status?: 'triggered' | 'executing' | 'completed' | 'failed';
          /** @enum {string} */
          triggerType?: 'event' | 'threshold' | 'schedule';
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            executions: {
              /** @enum {string} */
              actionType: 'ingest' | 'emit' | 'glia';
              actionVerb: string;
              completedAt: string | null;
              id: string;
              reflexName: string;
              result: {
                [key: string]: unknown;
              } | null;
              /** @enum {string} */
              status: 'triggered' | 'executing' | 'completed' | 'failed';
              triggerData: {
                [key: string]: unknown;
              } | null;
              /** @enum {string} */
              triggerType: 'event' | 'threshold' | 'schedule';
              triggeredAt: string;
            }[];
            total: number;
          };
        };
      };
    };
  };
  'reflex.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            history: {
              /** @enum {string} */
              actionType: 'ingest' | 'emit' | 'glia';
              actionVerb: string;
              completedAt: string | null;
              id: string;
              reflexName: string;
              result: {
                [key: string]: unknown;
              } | null;
              /** @enum {string} */
              status: 'triggered' | 'executing' | 'completed' | 'failed';
              triggerData: {
                [key: string]: unknown;
              } | null;
              /** @enum {string} */
              triggerType: 'event' | 'threshold' | 'schedule';
              triggeredAt: string;
            }[];
            reflex: {
              action: {
                scopes?: string[];
                target?: string;
                template?: string;
                /** @enum {string} */
                type: 'ingest' | 'emit' | 'glia';
                verb: string;
              };
              description: string;
              enabled: boolean;
              executionCount: number;
              lastExecutionAt: string | null;
              name: string;
              nextFireTime: string | null;
              trigger:
                | {
                    conditions?: {
                      scopes?: string[];
                      source?: string;
                      type?: string;
                    };
                    /** @enum {string} */
                    event:
                      | 'engram.created'
                      | 'engram.modified'
                      | 'engram.archived'
                      | 'engram.linked';
                    /** @enum {string} */
                    type: 'event';
                  }
                | {
                    /** @enum {string} */
                    metric: 'similar_count' | 'staleness_max' | 'topic_frequency';
                    scopes?: string[];
                    /** @enum {string} */
                    type: 'threshold';
                    value: number;
                  }
                | {
                    cron: string;
                    /** @enum {string} */
                    type: 'schedule';
                  };
            };
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'reflex.disable': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'reflex.enable': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'reflex.test': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            result: {
              /** @enum {string} */
              actionType: 'ingest' | 'emit' | 'glia';
              actionVerb: string;
              completedAt: string | null;
              id: string;
              reflexName: string;
              result: {
                [key: string]: unknown;
              } | null;
              /** @enum {string} */
              status: 'triggered' | 'executing' | 'completed' | 'failed';
              triggerData: {
                [key: string]: unknown;
              } | null;
              /** @enum {string} */
              triggerType: 'event' | 'threshold' | 'schedule';
              triggeredAt: string;
            } | null;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'scopes.list': {
    parameters: {
      query?: {
        prefix?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            scopes: {
              count: number;
              scope: string;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'scopes.filter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          includeSecret?: boolean;
          scopes: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            engrams: {
              contentHash: string;
              created: string;
              customFields: {
                [key: string]: unknown;
              };
              filePath: string;
              id: string;
              links: string[];
              modified: string;
              scopes: string[];
              source: string;
              /** @enum {string} */
              status: 'active' | 'archived' | 'consolidated' | 'stale';
              tags: string[];
              template: string | null;
              title: string;
              type: string;
              wordCount: number;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'scopes.reclassify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          dryRun?: boolean;
          fromScope: string;
          toScope: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count: number;
            ids: string[];
            rolled_back?: boolean;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'scopes.reconcile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          suggestedScopes: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            reconciled: {
              canonical: string;
              confidence: number;
              original: string;
              reason: string;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
  'scopes.validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          scope: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            errors?: string[];
            scope?: string;
            valid: boolean;
          };
        };
      };
    };
  };
  'tags.list': {
    parameters: {
      query?: {
        prefix?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            tags: {
              count: number;
              tag: string;
            }[];
          };
        };
      };
    };
  };
  'templates.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            templates: {
              custom_fields?: {
                [key: string]: {
                  description: string;
                  /** @enum {string} */
                  type: 'string' | 'number' | 'boolean' | 'string[]' | 'number[]' | 'boolean[]';
                };
              };
              default_scopes?: string[];
              description: string;
              name: string;
              required_fields?: string[];
              suggested_sections?: string[];
            }[];
          };
        };
      };
    };
  };
  'templates.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            template: {
              body: string;
              custom_fields?: {
                [key: string]: {
                  description: string;
                  /** @enum {string} */
                  type: 'string' | 'number' | 'boolean' | 'string[]' | 'number[]' | 'boolean[]';
                };
              };
              default_scopes?: string[];
              description: string;
              name: string;
              required_fields?: string[];
              suggested_sections?: string[];
            };
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
            messageKey?: string;
          };
        };
      };
    };
  };
}
