/**
 * Structural snapshot of the media pillar's public surface. Type now
 * lives in `manifest.generated.ts` and is regenerated by
 * `pnpm -F @pops/media-contract generate:manifest` (Theme 13 PRD-155).
 * This file remains the stable import path (`@pops/media-contract/manifest`)
 * so downstream consumers don't move with the generator output.
 */
export type { MediaContract } from './manifest.generated.js';
