// AUTOGENERATED by scripts/gen-row-schemas.mjs — do not edit by hand.
// Run `pnpm --filter @pops/db-types gen:row-schemas` to regenerate.

import { createSelectSchema } from 'drizzle-zod';

import { planSlots, planEntries } from './food-plan.js';

export const planSlotsRowSchema = createSelectSchema(planSlots);
export const planEntriesRowSchema = createSelectSchema(planEntries);
