// AUTOGENERATED by scripts/gen-row-schemas.mjs — do not edit by hand.
// Run `pnpm --filter @pops/db-types gen:row-schemas` to regenerate.

import { createSelectSchema } from 'drizzle-zod';

import { ingestSources } from './food-ingest-sources.js';

export const ingestSourcesRowSchema = createSelectSchema(ingestSources);
