// AUTOGENERATED by scripts/gen-row-schemas.mjs — do not edit by hand.
// Run `pnpm --filter @pops/db-types gen:row-schemas` to regenerate.

import { createSelectSchema } from 'drizzle-zod';

import {
  slugRegistry,
  ingredients,
  ingredientVariants,
  prepStates,
  ingredientAliases,
  ingredientTags,
} from './food-ingredients.js';

export const slugRegistryRowSchema = createSelectSchema(slugRegistry);
export const ingredientsRowSchema = createSelectSchema(ingredients);
export const ingredientVariantsRowSchema = createSelectSchema(ingredientVariants);
export const prepStatesRowSchema = createSelectSchema(prepStates);
export const ingredientAliasesRowSchema = createSelectSchema(ingredientAliases);
export const ingredientTagsRowSchema = createSelectSchema(ingredientTags);
