/**
 * Generates `src/contract/api-types.generated.ts` from the committed
 * OpenAPI spec. Output is a TS module exporting `paths` and `components`
 * types — zero runtime — that consumers compose with `openapi-fetch` to
 * get fully-typed HTTP calls without importing anything server-internal
 * from this pillar.
 *
 * Why this exists: the lego principle says consumers see only the
 * contract, and the contract surface for typed HTTP calls is OpenAPI.
 * `openapi-typescript` is the mature, language-agnostic tool that
 * turns OpenAPI into TS `paths`. Polyglot consumers (Rust, Swift)
 * skip this file and generate their own types from the JSON spec.
 *
 * Drift check (in `.github/workflows/lists-quality.yml`):
 *   pnpm --filter @pops/lists generate:api-types
 *   git diff --exit-code pillars/lists/src/contract/api-types.generated.ts
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const HERE = dirname(fileURLToPath(import.meta.url));
const OPENAPI_PATH = resolve(HERE, '..', 'openapi', 'lists.openapi.json');
const OUTPUT_PATH = resolve(HERE, '..', 'src', 'contract', 'api-types.generated.ts');

async function main(): Promise<void> {
  const ast = await openapiTS(new URL(`file://${OPENAPI_PATH}`));
  const body = astToString(ast);
  const header = [
    '/**',
    ' * AUTOGENERATED by scripts/generate-api-types.ts via openapi-typescript.',
    ' * Do not edit by hand — regenerate via `pnpm -F @pops/lists generate:api-types`.',
    ' * Drift check in lists-quality.yml fails on hand-edits.',
    ' */',
    '',
  ].join('\n');
  writeFileSync(OUTPUT_PATH, `${header}${body}`);

  // Match the formatting convention the rest of the pillar follows.
  execFileSync('pnpm', ['exec', 'oxfmt', '--write', OUTPUT_PATH], {
    cwd: resolve(HERE, '..'),
    stdio: 'inherit',
  });

  process.stdout.write(`[lists] wrote ${OUTPUT_PATH}\n`);
}

main().catch((err: unknown) => {
  process.stderr.write(`[lists] generate-api-types failed: ${String(err)}\n`);
  process.exit(1);
});
