// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type {
  AiAlertsAcknowledgeData,
  AiAlertsAcknowledgeErrors,
  AiAlertsAcknowledgeResponses,
  AiAlertsCreateRuleData,
  AiAlertsCreateRuleErrors,
  AiAlertsCreateRuleResponses,
  AiAlertsDeleteRuleData,
  AiAlertsDeleteRuleErrors,
  AiAlertsDeleteRuleResponses,
  AiAlertsGetRuleData,
  AiAlertsGetRuleErrors,
  AiAlertsGetRuleResponses,
  AiAlertsListData,
  AiAlertsListResponses,
  AiAlertsListRulesData,
  AiAlertsListRulesResponses,
  AiAlertsRunNowData,
  AiAlertsRunNowResponses,
  AiAlertsSeedDefaultRulesData,
  AiAlertsSeedDefaultRulesResponses,
  AiAlertsSetRuleEnabledData,
  AiAlertsSetRuleEnabledErrors,
  AiAlertsSetRuleEnabledResponses,
  AiAlertsUpdateRuleData,
  AiAlertsUpdateRuleErrors,
  AiAlertsUpdateRuleResponses,
  AiBudgetsGetBudgetStatusData,
  AiBudgetsGetBudgetStatusResponses,
  AiBudgetsListData,
  AiBudgetsListResponses,
  AiBudgetsUpsertData,
  AiBudgetsUpsertErrors,
  AiBudgetsUpsertResponses,
  AiObservabilityGetHistoryData,
  AiObservabilityGetHistoryResponses,
  AiObservabilityGetLatencyStatsData,
  AiObservabilityGetLatencyStatsResponses,
  AiObservabilityGetQualityMetricsData,
  AiObservabilityGetQualityMetricsResponses,
  AiObservabilityGetStatsData,
  AiObservabilityGetStatsResponses,
  AiProvidersGetData,
  AiProvidersGetResponses,
  AiProvidersHealthCheckData,
  AiProvidersHealthCheckResponses,
  AiProvidersListData,
  AiProvidersListResponses,
  AiProvidersUpsertData,
  AiProvidersUpsertErrors,
  AiProvidersUpsertResponses,
  AiUsageCacheStatsData,
  AiUsageCacheStatsResponses,
  AiUsageClearAllCacheData,
  AiUsageClearAllCacheResponses,
  AiUsageClearStaleCacheData,
  AiUsageClearStaleCacheErrors,
  AiUsageClearStaleCacheResponses,
  AiUsageGetHistoryData,
  AiUsageGetHistoryResponses,
  AiUsageGetStatsData,
  AiUsageGetStatsResponses,
  EntitiesCreateData,
  EntitiesCreateErrors,
  EntitiesCreateResponses,
  EntitiesDeleteData,
  EntitiesDeleteErrors,
  EntitiesDeleteResponses,
  EntitiesGetData,
  EntitiesGetErrors,
  EntitiesGetResponses,
  EntitiesListData,
  EntitiesListResponses,
  EntitiesUpdateData,
  EntitiesUpdateErrors,
  EntitiesUpdateResponses,
  FeaturesClearUserPreferenceData,
  FeaturesClearUserPreferenceErrors,
  FeaturesClearUserPreferenceResponses,
  FeaturesGetManifestsData,
  FeaturesGetManifestsErrors,
  FeaturesGetManifestsResponses,
  FeaturesIsEnabledData,
  FeaturesIsEnabledErrors,
  FeaturesIsEnabledResponses,
  FeaturesListData,
  FeaturesListErrors,
  FeaturesListResponses,
  FeaturesSetEnabledData,
  FeaturesSetEnabledErrors,
  FeaturesSetEnabledResponses,
  FeaturesSetUserPreferenceData,
  FeaturesSetUserPreferenceErrors,
  FeaturesSetUserPreferenceResponses,
  SearchSearchData,
  SearchSearchResponses,
  ServiceAccountsCreateData,
  ServiceAccountsCreateErrors,
  ServiceAccountsCreateResponses,
  ServiceAccountsListData,
  ServiceAccountsListErrors,
  ServiceAccountsListResponses,
  ServiceAccountsRevokeData,
  ServiceAccountsRevokeErrors,
  ServiceAccountsRevokeResponses,
  SettingsDeleteData,
  SettingsDeleteErrors,
  SettingsDeleteResponses,
  SettingsEnsureData,
  SettingsEnsureErrors,
  SettingsEnsureResponses,
  SettingsGetData,
  SettingsGetErrors,
  SettingsGetManyData,
  SettingsGetManyErrors,
  SettingsGetManyResponses,
  SettingsGetResponses,
  SettingsSetData,
  SettingsSetErrors,
  SettingsSetManyData,
  SettingsSetManyErrors,
  SettingsSetManyResponses,
  SettingsSetResponses,
  ShellManifestData,
  ShellManifestResponses,
  UsersGetData,
  UsersGetErrors,
  UsersGetResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List fired alerts with optional filters and pagination
 */
export const aiAlertsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiAlertsListData, ThrowOnError>
): RequestResult<AiAlertsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiAlertsListResponses, unknown, ThrowOnError>({
    url: '/ai-alerts',
    ...options,
  });

/**
 * List AI alert rules
 */
export const aiAlertsListRules = <ThrowOnError extends boolean = false>(
  options?: Options<AiAlertsListRulesData, ThrowOnError>
): RequestResult<AiAlertsListRulesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiAlertsListRulesResponses, unknown, ThrowOnError>({
    url: '/ai-alerts/rules',
    ...options,
  });

/**
 * Create an AI alert rule
 */
export const aiAlertsCreateRule = <ThrowOnError extends boolean = false>(
  options?: Options<AiAlertsCreateRuleData, ThrowOnError>
): RequestResult<AiAlertsCreateRuleResponses, AiAlertsCreateRuleErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AiAlertsCreateRuleResponses,
    AiAlertsCreateRuleErrors,
    ThrowOnError
  >({
    url: '/ai-alerts/rules',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Idempotently seed the default AI alert rules
 */
export const aiAlertsSeedDefaultRules = <ThrowOnError extends boolean = false>(
  options?: Options<AiAlertsSeedDefaultRulesData, ThrowOnError>
): RequestResult<AiAlertsSeedDefaultRulesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<AiAlertsSeedDefaultRulesResponses, unknown, ThrowOnError>({
    url: '/ai-alerts/rules/seed-defaults',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete an AI alert rule
 */
export const aiAlertsDeleteRule = <ThrowOnError extends boolean = false>(
  options: Options<AiAlertsDeleteRuleData, ThrowOnError>
): RequestResult<AiAlertsDeleteRuleResponses, AiAlertsDeleteRuleErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    AiAlertsDeleteRuleResponses,
    AiAlertsDeleteRuleErrors,
    ThrowOnError
  >({
    url: '/ai-alerts/rules/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single AI alert rule
 */
export const aiAlertsGetRule = <ThrowOnError extends boolean = false>(
  options: Options<AiAlertsGetRuleData, ThrowOnError>
): RequestResult<AiAlertsGetRuleResponses, AiAlertsGetRuleErrors, ThrowOnError> =>
  (options.client ?? client).get<AiAlertsGetRuleResponses, AiAlertsGetRuleErrors, ThrowOnError>({
    url: '/ai-alerts/rules/{id}',
    ...options,
  });

/**
 * Update an AI alert rule
 */
export const aiAlertsUpdateRule = <ThrowOnError extends boolean = false>(
  options: Options<AiAlertsUpdateRuleData, ThrowOnError>
): RequestResult<AiAlertsUpdateRuleResponses, AiAlertsUpdateRuleErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    AiAlertsUpdateRuleResponses,
    AiAlertsUpdateRuleErrors,
    ThrowOnError
  >({
    url: '/ai-alerts/rules/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Enable or disable an AI alert rule
 */
export const aiAlertsSetRuleEnabled = <ThrowOnError extends boolean = false>(
  options: Options<AiAlertsSetRuleEnabledData, ThrowOnError>
): RequestResult<AiAlertsSetRuleEnabledResponses, AiAlertsSetRuleEnabledErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    AiAlertsSetRuleEnabledResponses,
    AiAlertsSetRuleEnabledErrors,
    ThrowOnError
  >({
    url: '/ai-alerts/rules/{id}/enabled',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Run the AI alert evaluation cycle now
 */
export const aiAlertsRunNow = <ThrowOnError extends boolean = false>(
  options?: Options<AiAlertsRunNowData, ThrowOnError>
): RequestResult<AiAlertsRunNowResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<AiAlertsRunNowResponses, unknown, ThrowOnError>({
    url: '/ai-alerts/run',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Acknowledge a fired alert
 */
export const aiAlertsAcknowledge = <ThrowOnError extends boolean = false>(
  options: Options<AiAlertsAcknowledgeData, ThrowOnError>
): RequestResult<AiAlertsAcknowledgeResponses, AiAlertsAcknowledgeErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AiAlertsAcknowledgeResponses,
    AiAlertsAcknowledgeErrors,
    ThrowOnError
  >({
    url: '/ai-alerts/{id}/acknowledge',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List configured AI budgets
 */
export const aiBudgetsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiBudgetsListData, ThrowOnError>
): RequestResult<AiBudgetsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiBudgetsListResponses, unknown, ThrowOnError>({
    url: '/ai-budgets',
    ...options,
  });

/**
 * Create or update an AI budget (keyed by id)
 */
export const aiBudgetsUpsert = <ThrowOnError extends boolean = false>(
  options?: Options<AiBudgetsUpsertData, ThrowOnError>
): RequestResult<AiBudgetsUpsertResponses, AiBudgetsUpsertErrors, ThrowOnError> =>
  (options?.client ?? client).post<AiBudgetsUpsertResponses, AiBudgetsUpsertErrors, ThrowOnError>({
    url: '/ai-budgets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List AI budgets with live month-to-date usage and projected exhaustion
 */
export const aiBudgetsGetBudgetStatus = <ThrowOnError extends boolean = false>(
  options?: Options<AiBudgetsGetBudgetStatusData, ThrowOnError>
): RequestResult<AiBudgetsGetBudgetStatusResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiBudgetsGetBudgetStatusResponses, unknown, ThrowOnError>({
    url: '/ai-budgets/status',
    ...options,
  });

/**
 * Get AI observability history grouped by date
 */
export const aiObservabilityGetHistory = <ThrowOnError extends boolean = false>(
  options?: Options<AiObservabilityGetHistoryData, ThrowOnError>
): RequestResult<AiObservabilityGetHistoryResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiObservabilityGetHistoryResponses, unknown, ThrowOnError>({
    url: '/ai-observability/history',
    ...options,
  });

/**
 * Get AI latency percentiles (p50/p75/p95/p99/avg) and the slowest queries
 */
export const aiObservabilityGetLatencyStats = <ThrowOnError extends boolean = false>(
  options?: Options<AiObservabilityGetLatencyStatsData, ThrowOnError>
): RequestResult<AiObservabilityGetLatencyStatsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiObservabilityGetLatencyStatsResponses, unknown, ThrowOnError>({
    url: '/ai-observability/latency',
    ...options,
  });

/**
 * Get per-model AI quality metrics (cache/error/timeout/budget-block rates)
 */
export const aiObservabilityGetQualityMetrics = <ThrowOnError extends boolean = false>(
  options?: Options<AiObservabilityGetQualityMetricsData, ThrowOnError>
): RequestResult<AiObservabilityGetQualityMetricsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiObservabilityGetQualityMetricsResponses, unknown, ThrowOnError>(
    { url: '/ai-observability/quality', ...options }
  );

/**
 * Get AI observability stats (totals + per-provider/model/domain/operation breakdowns)
 */
export const aiObservabilityGetStats = <ThrowOnError extends boolean = false>(
  options?: Options<AiObservabilityGetStatsData, ThrowOnError>
): RequestResult<AiObservabilityGetStatsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiObservabilityGetStatsResponses, unknown, ThrowOnError>({
    url: '/ai-observability/stats',
    ...options,
  });

/**
 * List AI providers with their configured model pricing
 */
export const aiProvidersList = <ThrowOnError extends boolean = false>(
  options?: Options<AiProvidersListData, ThrowOnError>
): RequestResult<AiProvidersListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiProvidersListResponses, unknown, ThrowOnError>({
    url: '/ai-providers',
    ...options,
  });

/**
 * Create or update an AI provider and its model pricing (keyed by id)
 */
export const aiProvidersUpsert = <ThrowOnError extends boolean = false>(
  options?: Options<AiProvidersUpsertData, ThrowOnError>
): RequestResult<AiProvidersUpsertResponses, AiProvidersUpsertErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AiProvidersUpsertResponses,
    AiProvidersUpsertErrors,
    ThrowOnError
  >({
    url: '/ai-providers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Get a single AI provider with its models (null if unknown)
 */
export const aiProvidersGet = <ThrowOnError extends boolean = false>(
  options: Options<AiProvidersGetData, ThrowOnError>
): RequestResult<AiProvidersGetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<AiProvidersGetResponses, unknown, ThrowOnError>({
    url: '/ai-providers/{providerId}',
    ...options,
  });

/**
 * Run a live health check against an AI provider and persist the result
 */
export const aiProvidersHealthCheck = <ThrowOnError extends boolean = false>(
  options: Options<AiProvidersHealthCheckData, ThrowOnError>
): RequestResult<AiProvidersHealthCheckResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AiProvidersHealthCheckResponses, unknown, ThrowOnError>({
    url: '/ai-providers/{providerId}/health-check',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Clear the entire AI cache
 */
export const aiUsageClearAllCache = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageClearAllCacheData, ThrowOnError>
): RequestResult<AiUsageClearAllCacheResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).delete<AiUsageClearAllCacheResponses, unknown, ThrowOnError>({
    url: '/ai-usage/cache',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Get AI cache statistics (entry count, on-disk size)
 */
export const aiUsageCacheStats = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageCacheStatsData, ThrowOnError>
): RequestResult<AiUsageCacheStatsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiUsageCacheStatsResponses, unknown, ThrowOnError>({
    url: '/ai-usage/cache',
    ...options,
  });

/**
 * Remove AI cache entries older than maxAgeDays
 */
export const aiUsageClearStaleCache = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageClearStaleCacheData, ThrowOnError>
): RequestResult<AiUsageClearStaleCacheResponses, AiUsageClearStaleCacheErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AiUsageClearStaleCacheResponses,
    AiUsageClearStaleCacheErrors,
    ThrowOnError
  >({
    url: '/ai-usage/cache/prune',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Get AI usage history grouped by UTC date over an optional inclusive range
 */
export const aiUsageGetHistory = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageGetHistoryData, ThrowOnError>
): RequestResult<AiUsageGetHistoryResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiUsageGetHistoryResponses, unknown, ThrowOnError>({
    url: '/ai-usage/history',
    ...options,
  });

/**
 * Get overall AI usage statistics (cost, calls, cache hit rate, 30-day roll-up)
 */
export const aiUsageGetStats = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageGetStatsData, ThrowOnError>
): RequestResult<AiUsageGetStatsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AiUsageGetStatsResponses, unknown, ThrowOnError>({
    url: '/ai-usage/stats',
    ...options,
  });

/**
 * List entities with optional search / type filters and pagination
 */
export const entitiesList = <ThrowOnError extends boolean = false>(
  options?: Options<EntitiesListData, ThrowOnError>
): RequestResult<EntitiesListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<EntitiesListResponses, unknown, ThrowOnError>({
    url: '/entities',
    ...options,
  });

/**
 * Create an entity
 */
export const entitiesCreate = <ThrowOnError extends boolean = false>(
  options?: Options<EntitiesCreateData, ThrowOnError>
): RequestResult<EntitiesCreateResponses, EntitiesCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<EntitiesCreateResponses, EntitiesCreateErrors, ThrowOnError>({
    url: '/entities',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete an entity
 */
export const entitiesDelete = <ThrowOnError extends boolean = false>(
  options: Options<EntitiesDeleteData, ThrowOnError>
): RequestResult<EntitiesDeleteResponses, EntitiesDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<EntitiesDeleteResponses, EntitiesDeleteErrors, ThrowOnError>({
    url: '/entities/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single entity
 */
export const entitiesGet = <ThrowOnError extends boolean = false>(
  options: Options<EntitiesGetData, ThrowOnError>
): RequestResult<EntitiesGetResponses, EntitiesGetErrors, ThrowOnError> =>
  (options.client ?? client).get<EntitiesGetResponses, EntitiesGetErrors, ThrowOnError>({
    url: '/entities/{id}',
    ...options,
  });

/**
 * Update an entity
 */
export const entitiesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EntitiesUpdateData, ThrowOnError>
): RequestResult<EntitiesUpdateResponses, EntitiesUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<EntitiesUpdateResponses, EntitiesUpdateErrors, ThrowOnError>({
    url: '/entities/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Resolved feature status for the current user (admin Features page)
 */
export const featuresList = <ThrowOnError extends boolean = false>(
  options?: Options<FeaturesListData, ThrowOnError>
): RequestResult<FeaturesListResponses, FeaturesListErrors, ThrowOnError> =>
  (options?.client ?? client).get<FeaturesListResponses, FeaturesListErrors, ThrowOnError>({
    url: '/features',
    ...options,
  });

/**
 * List all registered feature manifests (sorted by order)
 */
export const featuresGetManifests = <ThrowOnError extends boolean = false>(
  options?: Options<FeaturesGetManifestsData, ThrowOnError>
): RequestResult<FeaturesGetManifestsResponses, FeaturesGetManifestsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    FeaturesGetManifestsResponses,
    FeaturesGetManifestsErrors,
    ThrowOnError
  >({ url: '/features/manifests', ...options });

/**
 * Runtime gate for a single feature in the current user context (404 on unknown key)
 */
export const featuresIsEnabled = <ThrowOnError extends boolean = false>(
  options: Options<FeaturesIsEnabledData, ThrowOnError>
): RequestResult<FeaturesIsEnabledResponses, FeaturesIsEnabledErrors, ThrowOnError> =>
  (options.client ?? client).get<FeaturesIsEnabledResponses, FeaturesIsEnabledErrors, ThrowOnError>(
    { url: '/features/{key}/enabled', ...options }
  );

/**
 * Set the system-level enabled state (400 when the gate is failing)
 */
export const featuresSetEnabled = <ThrowOnError extends boolean = false>(
  options: Options<FeaturesSetEnabledData, ThrowOnError>
): RequestResult<FeaturesSetEnabledResponses, FeaturesSetEnabledErrors, ThrowOnError> =>
  (options.client ?? client).put<
    FeaturesSetEnabledResponses,
    FeaturesSetEnabledErrors,
    ThrowOnError
  >({
    url: '/features/{key}/enabled',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove a per-user override (resolution falls back to the system default)
 */
export const featuresClearUserPreference = <ThrowOnError extends boolean = false>(
  options: Options<FeaturesClearUserPreferenceData, ThrowOnError>
): RequestResult<
  FeaturesClearUserPreferenceResponses,
  FeaturesClearUserPreferenceErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    FeaturesClearUserPreferenceResponses,
    FeaturesClearUserPreferenceErrors,
    ThrowOnError
  >({
    url: '/features/{key}/preference',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set a per-user override (400 when the feature is not user-scoped)
 */
export const featuresSetUserPreference = <ThrowOnError extends boolean = false>(
  options: Options<FeaturesSetUserPreferenceData, ThrowOnError>
): RequestResult<
  FeaturesSetUserPreferenceResponses,
  FeaturesSetUserPreferenceErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    FeaturesSetUserPreferenceResponses,
    FeaturesSetUserPreferenceErrors,
    ThrowOnError
  >({
    url: '/features/{key}/preference',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Search the core pillar's domains (entities) for the unified search engine
 */
export const searchSearch = <ThrowOnError extends boolean = false>(
  options?: Options<SearchSearchData, ThrowOnError>
): RequestResult<SearchSearchResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<SearchSearchResponses, unknown, ThrowOnError>({
    url: '/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List service accounts (admin only)
 */
export const serviceAccountsList = <ThrowOnError extends boolean = false>(
  options?: Options<ServiceAccountsListData, ThrowOnError>
): RequestResult<ServiceAccountsListResponses, ServiceAccountsListErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ServiceAccountsListResponses,
    ServiceAccountsListErrors,
    ThrowOnError
  >({ url: '/service-accounts', ...options });

/**
 * Mint a service account and return its one-time plaintext key (admin only)
 */
export const serviceAccountsCreate = <ThrowOnError extends boolean = false>(
  options?: Options<ServiceAccountsCreateData, ThrowOnError>
): RequestResult<ServiceAccountsCreateResponses, ServiceAccountsCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ServiceAccountsCreateResponses,
    ServiceAccountsCreateErrors,
    ThrowOnError
  >({
    url: '/service-accounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Revoke a service account by id (admin only)
 */
export const serviceAccountsRevoke = <ThrowOnError extends boolean = false>(
  options: Options<ServiceAccountsRevokeData, ThrowOnError>
): RequestResult<ServiceAccountsRevokeResponses, ServiceAccountsRevokeErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ServiceAccountsRevokeResponses,
    ServiceAccountsRevokeErrors,
    ThrowOnError
  >({
    url: '/service-accounts/{id}/revoke',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Batch-read settings by key (missing keys omitted)
 */
export const settingsGetMany = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsGetManyData, ThrowOnError>
): RequestResult<SettingsGetManyResponses, SettingsGetManyErrors, ThrowOnError> =>
  (options?.client ?? client).post<SettingsGetManyResponses, SettingsGetManyErrors, ThrowOnError>({
    url: '/settings/get-many',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Transactional batch write (all-or-nothing); returns the written mirror
 */
export const settingsSetMany = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsSetManyData, ThrowOnError>
): RequestResult<SettingsSetManyResponses, SettingsSetManyErrors, ThrowOnError> =>
  (options?.client ?? client).post<SettingsSetManyResponses, SettingsSetManyErrors, ThrowOnError>({
    url: '/settings/set-many',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete a single setting (404 on miss)
 */
export const settingsDelete = <ThrowOnError extends boolean = false>(
  options: Options<SettingsDeleteData, ThrowOnError>
): RequestResult<SettingsDeleteResponses, SettingsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<SettingsDeleteResponses, SettingsDeleteErrors, ThrowOnError>({
    url: '/settings/{key}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Read a single setting (null on miss)
 */
export const settingsGet = <ThrowOnError extends boolean = false>(
  options: Options<SettingsGetData, ThrowOnError>
): RequestResult<SettingsGetResponses, SettingsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<SettingsGetResponses, SettingsGetErrors, ThrowOnError>({
    url: '/settings/{key}',
    ...options,
  });

/**
 * Upsert a single setting
 */
export const settingsSet = <ThrowOnError extends boolean = false>(
  options: Options<SettingsSetData, ThrowOnError>
): RequestResult<SettingsSetResponses, SettingsSetErrors, ThrowOnError> =>
  (options.client ?? client).put<SettingsSetResponses, SettingsSetErrors, ThrowOnError>({
    url: '/settings/{key}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Write-once upsert-and-return for a single setting
 */
export const settingsEnsure = <ThrowOnError extends boolean = false>(
  options: Options<SettingsEnsureData, ThrowOnError>
): RequestResult<SettingsEnsureResponses, SettingsEnsureErrors, ThrowOnError> =>
  (options.client ?? client).post<SettingsEnsureResponses, SettingsEnsureErrors, ThrowOnError>({
    url: '/settings/{key}/ensure',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Read the boot-time install manifest (installed apps + overlays)
 */
export const shellManifest = <ThrowOnError extends boolean = false>(
  options?: Options<ShellManifestData, ThrowOnError>
): RequestResult<ShellManifestResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ShellManifestResponses, unknown, ThrowOnError>({
    url: '/shell/manifest',
    ...options,
  });

/**
 * Resolve a user URI (pops://core/user/<email>) for cross-pillar reconciliation
 */
export const usersGet = <ThrowOnError extends boolean = false>(
  options: Options<UsersGetData, ThrowOnError>
): RequestResult<UsersGetResponses, UsersGetErrors, ThrowOnError> =>
  (options.client ?? client).get<UsersGetResponses, UsersGetErrors, ThrowOnError>({
    url: '/users',
    ...options,
  });
