/**
 * AUTOGENERATED by scripts/generate-api-types.ts via openapi-typescript.
 * Do not edit by hand — regenerate via `pnpm -F @pops/ai generate:api-types`.
 */
export interface paths {
  '/ai-alerts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List fired alerts with optional filters and pagination */
    get: operations['aiAlerts.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-alerts/rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List AI alert rules */
    get: operations['aiAlerts.listRules'];
    put?: never;
    /** Create an AI alert rule */
    post: operations['aiAlerts.createRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-alerts/rules/seed-defaults': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Idempotently seed the default AI alert rules */
    post: operations['aiAlerts.seedDefaultRules'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-alerts/rules/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single AI alert rule */
    get: operations['aiAlerts.getRule'];
    put?: never;
    post?: never;
    /** Delete an AI alert rule */
    delete: operations['aiAlerts.deleteRule'];
    options?: never;
    head?: never;
    /** Update an AI alert rule */
    patch: operations['aiAlerts.updateRule'];
    trace?: never;
  };
  '/ai-alerts/rules/{id}/enabled': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Enable or disable an AI alert rule */
    patch: operations['aiAlerts.setRuleEnabled'];
    trace?: never;
  };
  '/ai-alerts/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run the AI alert evaluation cycle now */
    post: operations['aiAlerts.runNow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-alerts/{id}/acknowledge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Acknowledge a fired alert */
    post: operations['aiAlerts.acknowledge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-budgets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List configured AI budgets */
    get: operations['aiBudgets.list'];
    put?: never;
    /** Create or update an AI budget (keyed by id) */
    post: operations['aiBudgets.upsert'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-budgets/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List AI budgets with live month-to-date usage and projected exhaustion */
    get: operations['aiBudgets.getBudgetStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-observability/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get AI observability history grouped by date */
    get: operations['aiObservability.getHistory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-observability/latency': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get AI latency percentiles (p50/p75/p95/p99/avg) and the slowest queries */
    get: operations['aiObservability.getLatencyStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-observability/quality': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get per-model AI quality metrics (cache/error/timeout/budget-block rates) */
    get: operations['aiObservability.getQualityMetrics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-observability/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get AI observability stats (totals + per-provider/model/domain/operation breakdowns) */
    get: operations['aiObservability.getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-pricing/{provider}/{model}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resolve per-Mtok USD pricing { input, output } for a provider/model */
    get: operations['aiPricing.lookup'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List AI providers with their configured model pricing */
    get: operations['aiProviders.list'];
    put?: never;
    /** Create or update an AI provider and its model pricing (keyed by id) */
    post: operations['aiProviders.upsert'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-providers/{providerId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single AI provider with its models (null if unknown) */
    get: operations['aiProviders.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-providers/{providerId}/health-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run a live health check against an AI provider and persist the result */
    post: operations['aiProviders.healthCheck'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-usage/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get AI usage history grouped by UTC date over an optional inclusive range */
    get: operations['aiUsage.getHistory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-usage/record': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record one AI inference (internal; cross-pillar telemetry sink) */
    post: operations['aiIngest.record'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ai-usage/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get overall AI usage statistics (cost, calls, cache hit rate, 30-day roll-up) */
    get: operations['aiUsage.getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List effective values for every declared key (sensitive redacted) */
    get: operations['settings.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/get-many': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Batch-read settings by key (missing omitted; sensitive redacted) */
    post: operations['settings.getMany'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset declared keys to defaults (omit keys ⇒ reset all) */
    post: operations['settings.reset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/set-many': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transactional batch write (all-or-nothing); returns the written mirror */
    post: operations['settings.setMany'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a single setting (null on unset; sensitive redacted) */
    get: operations['settings.get'];
    /** Upsert a single declared setting */
    put: operations['settings.set'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/{key}/ensure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Internal-only write-once seed (encryption seed / client id) */
    post: operations['settings.ensure'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/{key}/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset a single setting to its manifest default */
    post: operations['settings.resetKey'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'aiAlerts.list': {
    parameters: {
      query?: {
        acknowledged?: 'true' | 'false';
        type?: 'budget-threshold' | 'error-spike' | 'latency-degradation';
        severity?: 'warning' | 'critical';
        startDate?: string;
        endDate?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            alerts: {
              acknowledged: boolean;
              acknowledgedAt: string | null;
              createdAt: string;
              id: number;
              message: string;
              metricValue: number;
              ruleId: number | null;
              scopeDetail: string | null;
              /** @enum {string} */
              severity: 'warning' | 'critical';
              thresholdValue: number;
              /** @enum {string} */
              type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
            }[];
            total: number;
          };
        };
      };
    };
  };
  'aiAlerts.listRules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            createdAt: string;
            enabled: boolean;
            id: number;
            scopeModel: string | null;
            scopeProvider: string | null;
            thresholdValue: number;
            /** @enum {string} */
            type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
            updatedAt: string;
            windowMinutes: number | null;
          }[];
        };
      };
    };
  };
  'aiAlerts.createRule': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          enabled?: boolean;
          scopeModel?: string | null;
          scopeProvider?: string | null;
          thresholdValue: number;
          /** @enum {string} */
          type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
          windowMinutes?: number | null;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            createdAt: string;
            enabled: boolean;
            id: number;
            scopeModel: string | null;
            scopeProvider: string | null;
            thresholdValue: number;
            /** @enum {string} */
            type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
            updatedAt: string;
            windowMinutes: number | null;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiAlerts.seedDefaultRules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            created: number;
          };
        };
      };
    };
  };
  'aiAlerts.getRule': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            createdAt: string;
            enabled: boolean;
            id: number;
            scopeModel: string | null;
            scopeProvider: string | null;
            thresholdValue: number;
            /** @enum {string} */
            type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
            updatedAt: string;
            windowMinutes: number | null;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiAlerts.deleteRule': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiAlerts.updateRule': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          enabled?: boolean;
          scopeModel?: string | null;
          scopeProvider?: string | null;
          thresholdValue?: number;
          /** @enum {string} */
          type?: 'budget-threshold' | 'error-spike' | 'latency-degradation';
          windowMinutes?: number | null;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            createdAt: string;
            enabled: boolean;
            id: number;
            scopeModel: string | null;
            scopeProvider: string | null;
            thresholdValue: number;
            /** @enum {string} */
            type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
            updatedAt: string;
            windowMinutes: number | null;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiAlerts.setRuleEnabled': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          enabled: boolean;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            createdAt: string;
            enabled: boolean;
            id: number;
            scopeModel: string | null;
            scopeProvider: string | null;
            thresholdValue: number;
            /** @enum {string} */
            type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
            updatedAt: string;
            windowMinutes: number | null;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiAlerts.runNow': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            alerts: {
              acknowledged: boolean;
              acknowledgedAt: string | null;
              channels: ('telegram' | 'nudge')[];
              createdAt: string;
              id: number;
              message: string;
              metricValue: number;
              ruleId: number | null;
              scopeDetail: string | null;
              /** @enum {string} */
              severity: 'warning' | 'critical';
              thresholdValue: number;
              /** @enum {string} */
              type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
            }[];
            candidates: number;
            deduped: number;
            rulesEvaluated: number;
          };
        };
      };
    };
  };
  'aiAlerts.acknowledge': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            acknowledged: boolean;
            acknowledgedAt: string | null;
            createdAt: string;
            id: number;
            message: string;
            metricValue: number;
            ruleId: number | null;
            scopeDetail: string | null;
            /** @enum {string} */
            severity: 'warning' | 'critical';
            thresholdValue: number;
            /** @enum {string} */
            type: 'budget-threshold' | 'error-spike' | 'latency-degradation';
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiBudgets.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            action: string;
            createdAt: string;
            id: string;
            monthlyCostLimit: number | null;
            monthlyTokenLimit: number | null;
            scopeType: string;
            scopeValue: string | null;
            updatedAt: string;
          }[];
        };
      };
    };
  };
  'aiBudgets.upsert': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          /** @enum {string} */
          action?: 'block' | 'warn' | 'fallback';
          id: string;
          monthlyCostLimit?: number;
          monthlyTokenLimit?: number;
          /** @enum {string} */
          scopeType: 'global' | 'provider' | 'operation';
          scopeValue?: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            action: string;
            createdAt: string;
            id: string;
            monthlyCostLimit: number | null;
            monthlyTokenLimit: number | null;
            scopeType: string;
            scopeValue: string | null;
            updatedAt: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiBudgets.getBudgetStatus': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            action: string;
            createdAt: string;
            currentCostUsage: number;
            currentTokenUsage: number;
            id: string;
            monthlyCostLimit: number | null;
            monthlyTokenLimit: number | null;
            percentageUsed: number | null;
            projectedExhaustionDate: string | null;
            scopeType: string;
            scopeValue: string | null;
            updatedAt: string;
          }[];
        };
      };
    };
  };
  'aiObservability.getHistory': {
    parameters: {
      query?: {
        provider?: string;
        model?: string;
        domain?: string;
        operation?: string;
        startDate?: string;
        endDate?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            records: {
              cacheHits: number;
              calls: number;
              costUsd: number;
              date: string;
              errors: number;
              inputTokens: number;
              outputTokens: number;
            }[];
            summary: {
              totalCacheHits: number;
              totalCalls: number;
              totalCostUsd: number;
            };
          };
        };
      };
    };
  };
  'aiObservability.getLatencyStats': {
    parameters: {
      query?: {
        provider?: string;
        model?: string;
        domain?: string;
        operation?: string;
        startDate?: string;
        endDate?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            avg: number;
            p50: number;
            p75: number;
            p95: number;
            p99: number;
            slowQueries: {
              contextId: string | null;
              createdAt: string;
              id: number;
              latencyMs: number;
              model: string;
              operation: string;
            }[];
          };
        };
      };
    };
  };
  'aiObservability.getQualityMetrics': {
    parameters: {
      query?: {
        provider?: string;
        model?: string;
        domain?: string;
        operation?: string;
        startDate?: string;
        endDate?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            byModel: {
              averageLatencyMs: number;
              budgetBlockRate: number;
              cacheHitRate: number;
              errorRate: number;
              model: string;
              provider: string;
              timeoutRate: number;
            }[];
          };
        };
      };
    };
  };
  'aiObservability.getStats': {
    parameters: {
      query?: {
        provider?: string;
        model?: string;
        domain?: string;
        operation?: string;
        startDate?: string;
        endDate?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            byDomain: {
              calls: number;
              costUsd: number;
              inputTokens: number;
              key: string;
              outputTokens: number;
            }[];
            byModel: {
              calls: number;
              costUsd: number;
              inputTokens: number;
              key: string;
              outputTokens: number;
            }[];
            byOperation: {
              calls: number;
              costUsd: number;
              inputTokens: number;
              key: string;
              outputTokens: number;
            }[];
            byProvider: {
              calls: number;
              costUsd: number;
              inputTokens: number;
              key: string;
              outputTokens: number;
            }[];
            cacheHitRate: number;
            errorRate: number;
            totalCalls: number;
            totalCostUsd: number;
            totalInputTokens: number;
            totalOutputTokens: number;
          };
        };
      };
    };
  };
  'aiPricing.lookup': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
        model: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            input: number;
            output: number;
          };
        };
      };
    };
  };
  'aiProviders.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            apiKeyRef: string | null;
            baseUrl: string | null;
            createdAt: string;
            id: string;
            lastHealthCheck: string | null;
            lastLatencyMs: number | null;
            models: {
              contextWindow: number | null;
              displayName: string | null;
              id: number;
              inputCostPerMtok: number;
              isDefault: boolean;
              modelId: string;
              outputCostPerMtok: number;
            }[];
            name: string;
            status: string;
            type: string;
            updatedAt: string;
          }[];
        };
      };
    };
  };
  'aiProviders.upsert': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          apiKeyRef?: string;
          /** Format: uri */
          baseUrl?: string;
          id: string;
          models?: {
            contextWindow?: number;
            displayName?: string;
            inputCostPerMtok?: number;
            isDefault?: boolean;
            modelId: string;
            outputCostPerMtok?: number;
          }[];
          name: string;
          /** @enum {string} */
          type: 'cloud' | 'local';
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            apiKeyRef: string | null;
            baseUrl: string | null;
            createdAt: string;
            id: string;
            lastHealthCheck: string | null;
            lastLatencyMs: number | null;
            models: {
              contextWindow: number | null;
              displayName: string | null;
              id: number;
              inputCostPerMtok: number;
              isDefault: boolean;
              modelId: string;
              outputCostPerMtok: number;
            }[];
            name: string;
            status: string;
            type: string;
            updatedAt: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'aiProviders.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        providerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            apiKeyRef: string | null;
            baseUrl: string | null;
            createdAt: string;
            id: string;
            lastHealthCheck: string | null;
            lastLatencyMs: number | null;
            models: {
              contextWindow: number | null;
              displayName: string | null;
              id: number;
              inputCostPerMtok: number;
              isDefault: boolean;
              modelId: string;
              outputCostPerMtok: number;
            }[];
            name: string;
            status: string;
            type: string;
            updatedAt: string;
          } | null;
        };
      };
    };
  };
  'aiProviders.healthCheck': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        providerId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error?: string;
            latencyMs: number;
            /** @enum {string} */
            status: 'active' | 'error';
          };
        };
      };
    };
  };
  'aiUsage.getHistory': {
    parameters: {
      query?: {
        startDate?: string;
        endDate?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            records: {
              apiCalls: number;
              cacheHits: number;
              cost: number;
              date: string;
              inputTokens: number;
              outputTokens: number;
            }[];
            summary: {
              totalApiCalls: number;
              totalCacheHits: number;
              totalCost: number;
            };
          };
        };
      };
    };
  };
  'aiIngest.record': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          cached: boolean;
          contextId?: string;
          costUsd: number;
          domain: string;
          errorMessage?: string;
          inputTokens: number;
          latencyMs: number;
          metadata?: {
            [key: string]: unknown;
          };
          model: string;
          operation: string;
          outputTokens: number;
          promptVersion?: string;
          provider: string;
          /** @enum {string} */
          status: 'success' | 'error' | 'timeout' | 'budget-blocked';
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 403 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  'aiUsage.getStats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            avgCostPerCall: number;
            cacheHitRate: number;
            last30Days?: {
              apiCalls: number;
              cacheHits: number;
              cost: number;
              inputTokens: number;
              outputTokens: number;
            };
            totalApiCalls: number;
            totalCacheHits: number;
            totalCost: number;
            totalInputTokens: number;
            totalOutputTokens: number;
          };
        };
      };
    };
  };
  'settings.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.getMany': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          keys: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            settings: {
              [key: string]: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          keys?: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            reset: string[];
            settings: {
              [key: string]: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.setMany': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          entries: {
            key: string;
            value: string;
          }[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            settings: {
              [key: string]: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'ai.model'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.logRetentionDays';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            } | null;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.set': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'ai.model'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.logRetentionDays';
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          value: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            };
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.ensure': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'ai.model'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.logRetentionDays';
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          value: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            };
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'settings.resetKey': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key:
          | 'ai.model'
          | 'ai.modelOverrides.query'
          | 'ai.modelOverrides.emit'
          | 'ai.modelOverrides.classifier'
          | 'ai.modelOverrides.entityExtractor'
          | 'ai.modelOverrides.scopeInference'
          | 'ai.modelOverrides.auditorContradiction'
          | 'ai.modelOverrides.patternContradiction'
          | 'ai.monthlyTokenBudget'
          | 'ai.budgetExceededFallback'
          | 'ai.logRetentionDays';
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            };
            message: string;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
}
