/**
 * Nudge log schema (PRD-084).
 *
 * Stores proactive nudges generated by background scans: consolidation
 * proposals, staleness alerts, pattern detections, and insight nudges.
 */
import { index, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const nudgeLog = sqliteTable(
  'nudge_log',
  {
    id: text('id').primaryKey(),
    type: text('type').notNull(),
    title: text('title').notNull(),
    body: text('body').notNull(),
    engramIds: text('engram_ids').notNull(),
    priority: text('priority').notNull(),
    status: text('status').notNull(),
    createdAt: text('created_at').notNull(),
    expiresAt: text('expires_at'),
    actedAt: text('acted_at'),
    actionType: text('action_type'),
    actionLabel: text('action_label'),
    actionParams: text('action_params'),
  },
  (table) => [
    index('idx_nudge_log_type').on(table.type),
    index('idx_nudge_log_status').on(table.status),
    index('idx_nudge_log_priority').on(table.priority),
    index('idx_nudge_log_created_at').on(table.createdAt),
  ]
);
