// AUTOGENERATED by scripts/gen-row-schemas.mjs — do not edit by hand.
// Run `pnpm --filter @pops/db-types gen:row-schemas` to regenerate.

import { createSelectSchema } from 'drizzle-zod';

import { aiInferenceDaily } from './ai-inference-daily.js';

export const aiInferenceDailyRowSchema = createSelectSchema(aiInferenceDaily);
