import { describe, expect, it } from 'vitest';

import { buildAllBoundaryRules, buildBoundaryRule, renderRulesFile } from './boundary-rules.js';
import { PILLARS } from './pillar-list.js';

describe('buildAllBoundaryRules', () => {
  it('produces exactly one rule per pillar', () => {
    const rules = buildAllBoundaryRules();
    expect(rules).toHaveLength(PILLARS.length);
    expect(rules.map((r) => r.name)).toEqual(
      PILLARS.map((p) => `no-cross-pillar-runtime-import-${p}`)
    );
  });

  it('marks every rule as error severity', () => {
    for (const rule of buildAllBoundaryRules()) {
      expect(rule.severity).toBe('error');
    }
  });
});

describe('buildBoundaryRule', () => {
  describe.each(PILLARS)('for pillar %s', (pillar) => {
    const rule = buildBoundaryRule(pillar);
    const toRegex = new RegExp(rule.to.path);
    const fromNotRegex = new RegExp(rule.from.pathNot);

    it('to.path matches the resolved workspace package path', () => {
      expect(toRegex.test(`packages/${pillar}-db/dist/index.js`)).toBe(true);
      expect(toRegex.test(`packages/${pillar}-db/dist/index.d.ts`)).toBe(true);
      expect(toRegex.test(`packages/${pillar}-db/dist/services/foo.js`)).toBe(true);
      expect(toRegex.test(`packages/${pillar}-db/src/index.ts`)).toBe(true);
    });

    it('to.path does not match the contract package or unrelated packages', () => {
      expect(toRegex.test(`packages/${pillar}-contract/dist/index.js`)).toBe(false);
      expect(toRegex.test('packages/types/dist/index.js')).toBe(false);
      expect(toRegex.test(`packages/${pillar}-db-something-else/dist/index.js`)).toBe(false);
    });

    it('from.pathNot excludes the owning api directory', () => {
      expect(fromNotRegex.test(`apps/pops-${pillar}-api/src/server.ts`)).toBe(true);
    });

    it('from.pathNot excludes the owning runtime package directory', () => {
      expect(fromNotRegex.test(`packages/${pillar}-db/src/index.ts`)).toBe(true);
      expect(fromNotRegex.test(`packages/${pillar}-db/__tests__/foo.test.ts`)).toBe(true);
    });

    it('from.pathNot does not exclude non-owning callers', () => {
      expect(fromNotRegex.test('apps/pops-api/src/modules/foo.ts')).toBe(false);
      expect(fromNotRegex.test('apps/pops-worker/src/index.ts')).toBe(false);
      expect(fromNotRegex.test('packages/app-finance/src/index.ts')).toBe(false);
    });

    it('from.pathNot does not exclude sibling pillars', () => {
      const others = PILLARS.filter((p) => p !== pillar);
      for (const other of others) {
        expect(fromNotRegex.test(`apps/pops-${other}-api/src/server.ts`)).toBe(false);
        expect(fromNotRegex.test(`packages/${other}-db/src/index.ts`)).toBe(false);
      }
    });

    it('comment names the contract package and links the PRD', () => {
      expect(rule.comment).toContain(`@pops/${pillar}-contract`);
      expect(rule.comment).toContain(`@pops/${pillar}-db`);
      expect(rule.comment).toContain(
        'docs/themes/13-pillar-finale/prds/156-consumer-import-discipline'
      );
    });
  });
});

describe('renderRulesFile', () => {
  it('emits a CJS module that exports contractBoundaryRules', () => {
    const text = renderRulesFile(buildAllBoundaryRules());
    expect(text).toContain('module.exports = { contractBoundaryRules }');
    expect(text).toContain('AUTOGENERATED');
  });

  it('produces stable output across runs', () => {
    const a = renderRulesFile(buildAllBoundaryRules());
    const b = renderRulesFile(buildAllBoundaryRules());
    expect(a).toBe(b);
  });
});
