import { getPillarLayout, PILLARS, type Pillar } from './pillar-list.js';

export interface BoundaryRule {
  readonly name: string;
  readonly severity: 'error';
  readonly comment: string;
  readonly from: { readonly pathNot: string };
  readonly to: { readonly path: string };
}

const PRD_PATH = 'docs/themes/13-pillar-finale/prds/156-consumer-import-discipline/README.md';

export function buildBoundaryRule(pillar: Pillar): BoundaryRule {
  const runtimePkg = `${pillar}-db`;
  const layout = getPillarLayout(pillar);
  return {
    name: `no-cross-pillar-runtime-import-${pillar}`,
    severity: 'error',
    comment:
      `Non-owning code must not import @pops/${runtimePkg}. ` +
      `Use @pops/${pillar}-contract for types and the pillar() SDK for calls. ` +
      `See ${PRD_PATH}`,
    from: {
      pathNot: `^(${layout.apiDir}|${layout.runtimeDir}|${layout.contractScriptsDir})/`,
    },
    to: {
      path: `^${layout.runtimeDir}/`,
    },
  };
}

export function buildAllBoundaryRules(): readonly BoundaryRule[] {
  return PILLARS.map(buildBoundaryRule);
}

function renderRule(rule: BoundaryRule): string {
  return [
    '  {',
    `    name: '${rule.name}',`,
    `    severity: '${rule.severity}',`,
    `    comment:`,
    `      '${rule.comment}',`,
    `    from: {`,
    `      pathNot: '${rule.from.pathNot}',`,
    `    },`,
    `    to: {`,
    `      path: '${rule.to.path}',`,
    `    },`,
    '  },',
  ].join('\n');
}

export function renderRulesFile(rules: readonly BoundaryRule[]): string {
  const header = [
    '// AUTOGENERATED by scripts/contract/generate-boundary-rules.ts.',
    '// Do not edit by hand. Run `pnpm lint:boundaries:generate` to refresh.',
    '',
    'const contractBoundaryRules = [',
  ].join('\n');
  const body = rules.map(renderRule).join('\n');
  const footer = ['];', '', 'module.exports = { contractBoundaryRules };', ''].join('\n');
  return `${header}\n${body}\n${footer}`;
}
