import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const MANIFEST_HEADER = '// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_JSON_PATH = resolve(HERE, '..', 'package.json');

export function readContractVersion(): string {
  const pkg: unknown = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8'));
  if (
    typeof pkg !== 'object' ||
    pkg === null ||
    !('version' in pkg) ||
    typeof (pkg as { version: unknown }).version !== 'string'
  ) {
    throw new Error('package.json must declare a string `version` field');
  }
  return (pkg as { version: string }).version;
}

export function renderManifest(version: string): string {
  return `${MANIFEST_HEADER}
// Regenerated by \`pnpm -F @pops/lists-contract generate:manifest\`.
// Source version pinned at generation time: ${version}
import type { AgendaItem } from './types/agenda-item.js';
import type { ListItem } from './types/list-item.js';
import type { Project } from './types/project.js';
import type { Tag } from './types/tag.js';
import type { ListsError } from './errors.js';
import type { ListsRouter } from './router.js';

export interface ListsContract {
  readonly pillar: 'lists';
  readonly version: string;
  readonly entities: {
    readonly agendaItem: AgendaItem;
    readonly listItem: ListItem;
    readonly project: Project;
    readonly tag: Tag;
  };
  readonly errors: ListsError;
  readonly router: ListsRouter;
}
`;
}

export const MANIFEST_OUTPUT_PATH = resolve(HERE, '..', 'src', 'manifest.generated.ts');
