/**
 * Local re-export of the food domain tables.
 *
 * Canonical definitions for food-owned tables live in `@pops/food-db`
 * (PRD-245 US-05). `aiInferenceLog` stays in `@pops/db-types` since the
 * AI surface is core-owned (core US-07).
 *
 * Services in this package import from here for ergonomics and so that
 * the food module's read surface stays self-describing.
 */
export { aiInferenceLog } from '@pops/db-types';
export {
  batchConsumptions,
  batches,
  ingestSources,
  ingredientAliases,
  ingredients,
  ingredientTags,
  ingredientVariants,
  ingredientWeights,
  planEntries,
  planSlots,
  prepStates,
  recipeLines,
  recipeRuns,
  recipes,
  recipeSteps,
  recipeTags,
  recipeVersionProposedSlugs,
  recipeVersionRejections,
  recipeVersions,
  slugRegistry,
  substitutions,
  unitConversions,
} from '@pops/food-db';
export type {
  BatchConsumptionInsert,
  BatchConsumptionRow,
  BatchInsert,
  BatchRow,
  CanonicalUnit,
  IngestSourceInsert,
  IngestSourceKind,
  IngestSourceRow,
  IngredientAliasInsert,
  IngredientAliasRow,
  IngredientInsert,
  IngredientRow,
  IngredientTagInsert,
  IngredientTagRow,
  IngredientVariantInsert,
  IngredientVariantRow,
  IngredientWeightInsert,
  IngredientWeightRow,
  PlanEntryInsert,
  PlanEntryRow,
  PlanSlotInsert,
  PlanSlotRow,
  PrepStateInsert,
  PrepStateRow,
  RecipeInsert,
  RecipeLineInsert,
  RecipeLineRow,
  RecipeRow,
  RecipeRunInsert,
  RecipeRunRow,
  RecipeStepInsert,
  RecipeStepRow,
  RecipeTagInsert,
  RecipeTagRow,
  RecipeVersionInsert,
  RecipeVersionProposedSlugInsert,
  RecipeVersionProposedSlugRow,
  RecipeVersionRejectionInsert,
  RecipeVersionRejectionRow,
  RecipeVersionRow,
  SlugRegistryInsert,
  SlugRegistryRow,
  SubstitutionInsert,
  SubstitutionRow,
  UnitConversionInsert,
  UnitConversionRow,
} from '@pops/db-types';
