/**
 * Local re-export of the food domain tables.
 *
 * Canonical definitions live in `@pops/db-types/src/schema/food.ts` so the
 * drizzle-kit config (which globs `packages/db-types/src/schema/*`) picks
 * them up and the rest of the platform sees a single schema barrel.
 *
 * Services in this package import from here for ergonomics and so that
 * the food module's read surface stays self-describing.
 */
export {
  batchConsumptions,
  batches,
  ingestSources,
  ingredientAliases,
  ingredients,
  ingredientVariants,
  ingredientWeights,
  planEntries,
  planSlots,
  prepStates,
  recipeLines,
  recipeRuns,
  recipes,
  recipeSteps,
  recipeTags,
  recipeVersionProposedSlugs,
  recipeVersionRejections,
  recipeVersions,
  slugRegistry,
  substitutions,
  unitConversions,
} from '@pops/db-types';
export type {
  BatchConsumptionInsert,
  BatchConsumptionRow,
  BatchInsert,
  BatchRow,
  CanonicalUnit,
  IngestSourceInsert,
  IngestSourceKind,
  IngestSourceRow,
  IngredientAliasInsert,
  IngredientAliasRow,
  IngredientInsert,
  IngredientRow,
  IngredientVariantInsert,
  IngredientVariantRow,
  IngredientWeightInsert,
  IngredientWeightRow,
  PlanEntryInsert,
  PlanEntryRow,
  PlanSlotInsert,
  PlanSlotRow,
  PrepStateInsert,
  PrepStateRow,
  RecipeInsert,
  RecipeLineInsert,
  RecipeLineRow,
  RecipeRow,
  RecipeRunInsert,
  RecipeRunRow,
  RecipeStepInsert,
  RecipeStepRow,
  RecipeTagInsert,
  RecipeTagRow,
  RecipeVersionInsert,
  RecipeVersionProposedSlugInsert,
  RecipeVersionProposedSlugRow,
  RecipeVersionRejectionInsert,
  RecipeVersionRejectionRow,
  RecipeVersionRow,
  SlugRegistryInsert,
  SlugRegistryRow,
  SubstitutionInsert,
  SubstitutionRow,
  UnitConversionInsert,
  UnitConversionRow,
} from '@pops/db-types';
