// AUTOGENERATED by scripts/gen-row-schemas.mjs — do not edit by hand.
// Run `pnpm --filter @pops/db-types gen:row-schemas` to regenerate.

import { createSelectSchema } from 'drizzle-zod';

import { conversations, messages, conversationContext } from './ego.js';

export const conversationsRowSchema = createSelectSchema(conversations);
export const messagesRowSchema = createSelectSchema(messages);
export const conversationContextRowSchema = createSelectSchema(conversationContext);
