/**
 * Stable hand-authored manifest surface for the food pillar. The
 * `FoodContract` type lives in `manifest.generated.ts` (regenerated by
 * `generate:manifest`); this file owns the runtime `ModuleManifest` value
 * the pillar self-registers with. Food declares no settings dimension.
 */
import type { ModuleManifest } from '@pops/types';

export type { FoodContract } from './manifest.generated.js';

export const foodManifest: ModuleManifest = {
  id: 'food',
  name: 'Food',
  version: '0.1.0',
  surfaces: ['app'],
  description: 'Recipes, ingredients, meal planning, and multimodal ingestion.',
};
